SchwarzIT/onyx

.github/workflows/deploy.yml
The updated CF variables were added as environment secrets, therefore the pipelines must be updated accordingly
=> fix(pipeline): make use of environment in deployment

.changeset/shiny-lies-cough.md, packages/storybook-utils/src/theme.ts
Fix breakpoint name to match the key name which was updated by Jannick
=> refactor(storybook-utils): rename breakpoints

CONTRIBUTING.md, README.md
closes #42 
Update the CONTRIBUTING.md information by referencing the Code of Conduct and our Technical Guidelines.
We might add process information on how we decide which features will be approved in the future, when it is further defined.
=> docs: update CONTRIBUTING.md

apps/docs/.cloud-foundry/manifest-prod.yml, packages/sit-onyx/.cloud-foundry/manifest-prod.yml
Add prod manifests for Cloud Foundry for our deployment.
=> chore: add prod manifests

.changeset/wild-days-admire.md, .github/ISSUE_TEMPLATE/bug_report.yml, .github/ISSUE_TEMPLATE/feature_request.yml, .github/workflows/import-figma.yml, CONTRIBUTING.md, SECURITY.md, apps/docs/src/.vitepress/config.ts, apps/docs/src/.vitepress/utils.ts, apps/docs/src/getting-started.md, apps/docs/src/i18n/index.md, apps/docs/src/i18n/languages.data.ts, apps/docs/src/index.md, apps/docs/src/packages/storybook-utils.md, apps/docs/src/packages/vitepress-theme.md, apps/docs/src/team.md, apps/docs/src/typography.md, packages/headless/README.md, packages/sit-onyx/README.md, packages/sit-onyx/src/components/TestInput/TestInput.vue, packages/sit-onyx/src/i18n/index.ts, packages/storybook-utils/CHANGELOG.md, packages/storybook-utils/src/preview.ts, packages/storybook-utils/src/theme.ts, packages/vitepress-theme/README.md, packages/vitepress-theme/package.json, packages/vitepress-theme/src/index.scss, packages/vitepress-theme/src/mixins.scss
Write onyx in lowercase throughout the whole code base
=> docs: write onyx in all lowercase

apps/docs/src/index.md
Update broken getting started link
=> docs: update broken getting started link

apps/alpha-test-app/package.json, apps/docs/package.json, packages/sit-onyx/package.json
Add a "start" scripts as an alias for the "dev" command.
=> chore(scripts): add start alias for dev command

apps/docs/src/.vitepress/config.ts, apps/docs/src/.vitepress/utils.ts, apps/docs/src/development/[name].paths.ts
remove .DS_Store file from component sidebar
=> docs(components): remove .DS_Store file from component sidebar

apps/docs/src/brand/team.md
=> docs: rename Jannick to "Keller" 🤵🏽‍♂️

packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.vue
closes #220
use global required/optional marker classes
=> refactor(OnyxCheckbox): use global required/optional marker classes

packages/storybook-utils/package.json, pnpm-lock.yaml
Fixes an error which breaks storybook on production.
The error is caused by using version 7 of storybook with our currently used storybook snapshot version.
=> fix: storybook "ye" bug

packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.vue
=> fix(OnyxRadioButton): using unlisted animation timing

packages/sit-onyx/package.json, packages/storybook-utils/package.json, pnpm-lock.yaml
Update Storybook to version 8 release candidate
=> chore: update to Storybook 8 rc

packages/sit-onyx/src/components/OnyxLoadingIndicator/LoadingDots.vue
relates to #390
Based on: https://github.com/SchwarzIT/onyx/issues/390#issuecomment-1978698587
=> chore(OnyxLoadingIndicator): update keyframes

CODEOWNERS
Update codeowners to the new onyx-dev team
=> chore: update codeownes

.gitignore
=> chore: add .env files to gitignore

.github/workflows/playwright-screenshots.yml
Add workflow input to delete snapshots.
=> chore: add workflow input to delete snapshots

apps/alpha-test-app/src/views/HomeView.vue, packages/sit-onyx/src/components/OnyxListbox/OnyxListbox.stories.ts
Relates to #564
Add listbox example to demo app
=> docs: add listbox example to demo app

apps/docs/src/index.data.ts
Relates to #744
Change status of OnyxEmpty to implemented.
=> docs: mark OnyxEmpty as implemented

packages/sit-onyx/src/components/OnyxEmpty/OnyxEmpty.vue
Relates to #338 
Use component layer for new OnyxEmpty component
=> refactor(OnyxEmpty): use component layer

.github/workflows/playwright.yml
Include added files in screenshot pull request.
=> chore(screenshots): include added files in pull request

apps/docs/src/index.data.ts
Relates to #916
Update component status of badge, button and switch to `done`
=> docs: update component status

packages/sit-onyx/src/components/OnyxNavSeparator/OnyxNavSeparator.stories.ts
=> docs(OnyxNavSeparator): fix Storybook title

apps/docs/package.json, apps/docs/src/.vitepress/components/ComponentRoadmap.stories.ts, apps/docs/src/.vitepress/components/DesignTokenHeader.vue, package.json, packages/sit-onyx/src/components/OnyxNavItem/OnyxNavItem.stories.ts
- we used some button/badge colors which we renamed so I fixed them.
- also I noticed that our docs are not type-checked in CI so I also added type checking for it
=> fix(docs): update invalid button/badge colors

packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.stories.ts
Relates to https://github.com/SchwarzIT/onyx/issues/565#issuecomment-2144776218
=> docs: fix `OnyxSelect` multiselect example

.changeset/chilled-bobcats-learn.md, packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.stories.ts, packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue, packages/sit-onyx/src/components/OnyxSelect/types.ts
Relates to https://github.com/SchwarzIT/onyx/issues/565#issuecomment-2144776218
- hide check all when searching
- update docs
=> fix(OnyxSelect): hide check all when searching

packages/sit-onyx/.storybook/public/favicon.svg
closes #1290
Add favicon to Storybook (same as for our docs)
=> feat: add Storybook favicon

packages/sit-onyx/.storybook/pages/introduction.mdx
=> chore(Storybook): add imprint link to storybook

package.json, pnpm-lock.yaml
Relates to #1393
This fixes the bug now now. I will try to investigate this further
=> docs: fix Storybook examples not working with slots

packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.vue
Relates to #1348 
Adjust styles order to avoid deprecation warning
=> fix(OnyxStepper): Adjust styles to avoid deprecation warning

packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.ct.tsx, packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.ct.tsx, packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.ct.tsx
Relates to #1312 
Follow-up on 
- #1588
=> chore: add tests for the label/error title feature

.changeset/smooth-lions-speak.md, packages/sit-onyx/CHANGELOG.md
The docs build currently fails due to a invalid changelog entry
=> chore: fix docs build

apps/docs/src/.vitepress/components/DensitySelection.vue, apps/docs/src/.vitepress/components/DesignTokenBadge.vue, apps/docs/src/.vitepress/components/DesignTokenCard.vue, apps/docs/src/.vitepress/components/OnyxColorPalettes.vue, apps/docs/src/.vitepress/components/OnyxSpacingTokens.vue, apps/docs/src/.vitepress/utils-browser.ts, apps/docs/src/tokens/spacings.md
relates to #1210
Update spacing token docs to also include the new density tokens
=> docs: show density tokens

.changeset/ten-pigs-beg.md, apps/demo-app/src/views/HomeView.vue, packages/sit-onyx/src/index.ts
Relates to #1348 
Export `OnyxStepper` component so it can be used by projects
=> fix: export OnyxStepper

packages/sit-onyx/.storybook/theme-switch.ts, packages/sit-onyx/src/components/OnyxListItem/OnyxListItem.stories.ts, packages/storybook-utils/src/types.ts
closes #1617
- show selected theme in theme selection
- fix sorting of ListItem in the sidebar
=> docs: use dynamic title for theme selection

apps/playground/package.json, apps/playground/playwright.config.ts, apps/playground/tests/playground.spec.ts, package.json, turbo.json
Relates to https://github.com/SchwarzIT/onyx/issues/1489#issuecomment-2264751671
- setup Playwright integration tests for the playground
- add test for persisting onyx version in URL
=> test(playground): setup Playwright tests

apps/demo-app/src/components/SelectDemo.vue
Relates to #1392 
Added new example of OnyxSelect with list description in the demo app.
=> feat(demo-app): Add example in demo app

apps/docs/src/development/theming.md, packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxColorSchemeDialog/OnyxColorSchemeDialog.stories.ts
Move `OnyxColorSchemeDialog` to support components since `OnyxMenuItem` is the intended main component
=> docs: categorize `OnyxColorSchemeDialog` as support component

.changeset/hip-hats-know.md, packages/headless/src/composables/comboBox/createComboBox.ts, packages/headless/src/composables/listbox/TestListbox.vue, packages/headless/src/composables/listbox/createListbox.ts
Relates to #1734
A window auto scroll behavior was detected when programmatically changing the active option inside a listbox without opening it.
=> fix(listbox): Fix auto scrolling behavior when it's closed

packages/sit-onyx/src/components/OnyxFormElement/OnyxFormElement.ct.tsx, packages/sit-onyx/src/components/OnyxFormElement/TestWrapper.vue
=> chore(OnyxFormElement): implement form element unique id tests

.github/workflows/import-figma-icons.yml, package.json
Relates to #939
Do not fail icon import workflow/pipeline when nothing changed, see [this successful workflow run](https://github.com/SchwarzIT/onyx/actions/runs/10593460712)
=> fix(icon-workflow): succeed if no icons changed

.changeset/thick-terms-serve.md, apps/docs/src/.vitepress/components/OnyxBorderRadiusTokens.vue
Relates to #199 
Fix background color of borders token preview
=> fix(OnyxBorderRadiusTokens): Fix background color of borders token preview

.github/workflows/import-figma-icons.yml, .github/workflows/import-figma.yml
Add Figma links to auto generated PRs so its easier to access/debug them if e.g. icons are broken
=> ci: add Figma links to auto generated PRs

packages/sit-onyx/.storybook/main.ts, packages/sit-onyx/package.json, pnpm-lock.yaml
Relates to #641 
Impelement a11y addon in Storybook
=> chore: Impelement a11y addon

packages/sit-onyx/src/components/examples/FormExample/FormExample.vue
=> docs(Form Elements): fix example form grid

packages/sit-onyx/.storybook/main.ts
=> chore(storybook): Fix storybook cache error

apps/demo-app/src/views/HomeView.vue
Relates to #1602 
Implement skeleton injected prop in DemoApp
=> feat(demoApp): Implement skeleton injected prop in DemoApp

packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.stories.ts, packages/sit-onyx/src/components/OnyxDataGrid/features/all.ts, packages/sit-onyx/src/components/OnyxDataGrid/features/index.ts, packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/TestCase.vue, packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/sorting.ct.tsx, packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/sorting.spec.ts, packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/sorting.stories.ts, packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/sorting.ts, packages/sit-onyx/src/components/OnyxDataGrid/types.ts, packages/sit-onyx/src/components/examples/DataGrid/SortingDataGrid.vue
Closes [#2082](https://github.com/SchwarzIT/onyx/issues/2082)
=> docs: fix sort action not always logging

.github/ISSUE_TEMPLATE/98-dev-story.yml, .github/ISSUE_TEMPLATE/99-ux-story.yml
Improve/Remove whitespaces.
Closes #2164
=> chore: Fix whitespaces in issue templates

.changeset/lemon-lions-provide.md, .changeset/tasty-socks-fail.md, apps/docs/src/development/index.md, apps/docs/src/development/packages/storybook-utils.md, packages/headless/src/composables/menuButton/createMenuButton.ts, packages/headless/src/utils/timer.ts, packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.stories.ts, packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/OnyxFlyoutMenu.stories.ts, packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxNavItem/OnyxNavItem.vue, packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxUserMenu/OnyxUserMenu.ct.tsx, packages/storybook-utils/package.json, packages/storybook-utils/src/actions.ts, pnpm-lock.yaml
- docs(docs): add hint about Vue app being a prerequisite
- docs(sit-onyx): add logging for `OnyxNavButton` and `OnyxNavItem` in `OnyxNavbar` example to make usage clearer.
- feat(storybook-utils): add `createActionLoggerWrapper` util to allow event logging for slotted child components
- feat(sit-onyx): `OnyxFlyoutMenu` opens immediately when hovered, but has debounced closing 
- feat(headless): `debounce` util exposes an `abort()` method which allows for cancelling outstanding callbacks
=> feat: minor fixes and doc updated

.github/templates/node-setup/action.yml, .github/workflows/check.yml, .github/workflows/import-figma-icons.yml, .github/workflows/import-figma.yml, .github/workflows/playwright.yml, .github/workflows/release.yml, apps/docs/src/cached.ts
- added `pnpm` and `node` setup GitHub workflow
- fixed caching path on write for vitepress cache
=> fix: caching for pipeline

apps/demo-app/src/views/HomeView.vue
Relates to #1818
Add date picker example to demo app.
=> docs: add OnyxDatePicker to demo app

apps/docs/src/.vitepress/components/ComponentCard.stories.ts, apps/docs/src/.vitepress/components/ComponentCard.vue, apps/docs/src/.vitepress/components/ComponentRoadmap.stories.ts, apps/docs/src/.vitepress/components/ComponentRoadmap.vue, apps/docs/src/.vitepress/components/ComponentStatusBadge.vue, apps/docs/src/index.data.ts
Relates to #2298 
- Remove due indicator
- Replace icon buttons with icons
- Use new icons
=> feat(docs): Implement new component overview

.changeset/ninety-dancers-mate.md, packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.stories.ts, packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.vue, packages/sit-onyx/src/components/OnyxBottomBar/types.ts, packages/sit-onyx/src/index.ts
Relates to #2290 
Implement OnyxBottomBar component
=> feat(OnyxBottomBar): Implement OnyxBottomBar

packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.stories.ts, packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.ct.tsx
Relates to #2290 
Improve storybook example
=> fix(OnyxBottomBar): Improve storybook example

apps/demo-app/src/views/DataGridView.vue, packages/sit-onyx/src/index.ts
Relates to #2293 
- Add example in the demo-app
=> feat(demo-app): Add data grid example in the demo-app

packages/sit-onyx/src/components/examples/OnyxCard/DetailsCardExample.vue, packages/sit-onyx/src/components/examples/OnyxCard/HeadlineCardExample.vue, packages/sit-onyx/src/components/examples/OnyxCard/IconCardExample.vue, packages/sit-onyx/src/components/examples/OnyxCard/ImageCardExample.vue, packages/sit-onyx/src/components/examples/OnyxCard/KPICardExample.vue, packages/sit-onyx/src/components/examples/OnyxCard/OnyxCardExamples.stories.ts
Relates to 2383
Implement more card examples from: https://www.figma.com/design/kujUj0MWtx45FbLd3zUWjL/Card-Follow-Up?node-id=9121-120283&m=dev
=> docs(OnyxCard): implement more examples

packages/sit-onyx/src/components/examples/OnyxCard/IconCardExample.vue, packages/sit-onyx/src/components/examples/OnyxCard/ImageCardExample.vue
https://github.com/SchwarzIT/onyx/issues/2383#issuecomment-2593206795
=> docs(OnyxCard): update flyout menu examples to open on click instead of hover

apps/demo-app/package.json, package.json, packages/nuxt/package.json, pnpm-lock.yaml
=> chore: update to pnpm 10

.github/pull_request_template.md
Add self review checkbox to the PR template and update the existing ones for more clarification
=> chore: add self review to PR template

packages/sit-onyx/src/components/OnyxTable/OnyxTable.vue
=> fix(OnyxTable): fix clipping issue with hover effect and popovers

packages/sit-onyx/src/components/OnyxDataGrid/examples/ResizingExample.vue, packages/sit-onyx/src/components/OnyxDataGrid/features/resizing/resizing.scss
Relates to #2502 
- Use the new type: "date" for the birthday column of the Storybook example
- Add headline for the Storybook example?
=> fix(OnyxDataGrid): Apply ticket feedback

packages/headless/src/composables/comboBox/SelectOnlyCombobox.vue, packages/headless/src/composables/comboBox/TestCombobox.vue, packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/TestWrapper.ct.vue, packages/sit-onyx/src/components/OnyxTextarea/OnyxTextarea.vue
There are currently a few existing eslint warnings/errors that are fixed in this PR.
=> chore: fix existing eslint errors/warnings

.changeset/bumpy-colts-double.md, packages/sit-onyx/src/components/OnyxNavBar/modules/index.ts, packages/sit-onyx/src/index.ts
=> feat: Export OnyxFormElement and OnyxNavItemFacade components

packages/sit-onyx/src/components/OnyxAccordion/OnyxAccordion.stories.ts, packages/sit-onyx/src/components/OnyxBreadcrumb/OnyxBreadcrumb.stories.ts, packages/sit-onyx/src/components/OnyxBreadcrumbItem/OnyxBreadcrumbItem.stories.ts, packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.stories.ts, packages/sit-onyx/src/components/OnyxDataGrid/examples/OnyxDataGridFeatureExamples.stories.ts, packages/sit-onyx/src/components/OnyxDrawer/OnyxDrawer.stories.ts, packages/sit-onyx/src/components/OnyxIcon/OnyxIcon.stories.ts, packages/sit-onyx/src/components/OnyxInfoCard/OnyxInfoCard.stories.ts, packages/sit-onyx/src/components/OnyxNotificationDot/OnyxNotificationDot.stories.ts, packages/sit-onyx/src/components/OnyxNotifications/OnyxNotifications.stories.ts, packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.stories.ts
sprintly clean-up of the "new" badges
=> chore(docs): remove outdated new badges

packages/sit-onyx/src/components/OnyxAvatar/OnyxAvatar.stories.ts, packages/sit-onyx/src/components/OnyxAvatarStack/OnyxAvatarStack.stories.ts, packages/sit-onyx/src/components/OnyxBadge/OnyxBadge.stories.ts, packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.stories.ts, packages/sit-onyx/src/components/OnyxDialog/OnyxDialog.stories.ts, packages/sit-onyx/src/components/OnyxForm/OnyxForm.stories.ts, packages/sit-onyx/src/components/OnyxHeadline/OnyxHeadline.stories.ts, packages/sit-onyx/src/components/OnyxIcon/OnyxIcon.stories.ts, packages/sit-onyx/src/components/OnyxIconButton/OnyxIconButton.stories.ts, packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.stories.ts, packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.stories.ts, packages/sit-onyx/src/components/OnyxSystemButton/OnyxSystemButton.stories.ts, packages/sit-onyx/src/components/OnyxTable/OnyxTable.stories.ts, packages/sit-onyx/src/components/OnyxTabs/OnyxTabs.stories.ts, packages/sit-onyx/src/components/OnyxTextarea/OnyxTextarea.stories.ts, packages/sit-onyx/src/components/OnyxToast/OnyxToast.stories.ts, packages/sit-onyx/src/components/OnyxTooltip/OnyxTooltip.stories.ts
=> Updated descriptions

packages/sit-onyx/src/components/OnyxBottomBar/OnyxBottomBar.stories.ts, packages/sit-onyx/src/components/OnyxCard/OnyxCard.stories.ts, packages/sit-onyx/src/components/OnyxImage/OnyxImage.stories.ts, packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.stories.ts, packages/sit-onyx/src/components/OnyxTabs/OnyxTabs.stories.ts
Relates to #3133 
Minor fixes on descriptions
=> docs(components): Minor updates for some Storybook component descriptions

.changeset/beige-pans-scream.md, packages/sit-onyx/src/components/OnyxDataGrid/examples/SkeletonExample.vue, packages/sit-onyx/src/components/OnyxDataGrid/features/base/base.scss, packages/sit-onyx/src/components/OnyxDataGrid/features/base/base.ts, packages/sit-onyx/src/components/OnyxTable/examples/OnyxTableSkeletonExample.vue
=> fix(OnyxDataGrid, OnyxTable): fix hover effect is shown when in skeleton mode

apps/docs/src/index.data.ts
Some component links were outdated/broken, so I updated it to not confuse users.
=> chore: update outdated index components

.changeset/light-eagles-care.md, apps/demo-app/tsconfig.json, apps/playground/tsconfig.app.json, package.json, packages/chartjs-plugin/package.json, packages/headless/package.json, packages/headless/src/utils/builder.ts, packages/headless/vite.config.ts, packages/nuxt-docs/package.json, packages/sit-onyx/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
Storybook had issues with missing dist files of the headless package.
=> chore: fix storybook build

packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxMenuItem/OnyxMenuItem.vue, packages/sit-onyx/src/types/utils.spec-d.ts, packages/sit-onyx/src/types/utils.ts, packages/sit-onyx/src/utils/attrs.spec.ts, packages/sit-onyx/src/utils/attrs.ts
- improve typing of `mergeVueProps`utility
=> chore(mergeVueProps): improve util typing of mergeVueProps

packages/sit-onyx/src/components/OnyxGlobalFAB/OnyxGlobalFAB.vue, packages/sit-onyx/src/components/OnyxGlobalFAB/examples/GlobalExample.vue, packages/sit-onyx/src/components/OnyxGlobalFAB/useGlobalFAB.spec.ts, packages/sit-onyx/src/components/OnyxGlobalFAB/useGlobalFAB.ts, packages/sit-onyx/src/components/OnyxSidebar/OnyxSidebar.vue, packages/sit-onyx/src/i18n/locales/de-DE.json, packages/sit-onyx/src/i18n/locales/en-US.json
=> implement PR feedback for #3782

.github/ISSUE_TEMPLATE/98-dev-story.yml, .github/ISSUE_TEMPLATE/99-ux-story.yml
Update the issue templates for UX and DEV tickets as discussed in the meeting.
Both templates are enhanced with a checklist that should take care of avoiding common pain points.
=> docs: update UX and DEV issue template

.changeset/smart-webs-press.md, packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.vue
=> fix(OnyxStepper): Fix id prop not being applied to the native input element

.github/workflows/release.yml, apps/demo-app/.cloud-foundry/manifest-dev.yml, apps/demo-app/.cloud-foundry/manifest-prod.yml, apps/demo-app/app/components/UserMenu.vue, apps/demo-app/layers/blueprint/nuxt.config.ts, apps/demo-app/nuxt.config.ts
Relates to #3986 
Setup deployment for our (public) demo app. The deployment for the internal demo app (with Schwarz internal brand themes) will be done separately.
=> chore: setup deployment for demo app

.changeset/tasty-places-trade.md, packages/sit-onyx/src/components/OnyxDialog/examples/DefaultExample.vue, packages/sit-onyx/src/components/OnyxDialog/examples/DescriptionExample.vue, packages/sit-onyx/src/components/OnyxDialog/examples/SupportExample.vue, packages/sit-onyx/src/components/OnyxDialog/examples/URLExample.vue, packages/sit-onyx/src/index.ts
Relates to #3907
- export OnyxDialog
- fixed imports in StoryBookExamples
=> feat(OnyxDialog): export OnyxDialog correctly

packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.stories.ts, packages/sit-onyx/src/components/OnyxDataGrid/examples/GroupedDataExample.vue
Relates to #4108
Add example on how to use the data grid column groups
=> docs(OnyxDataGrid): implement column groups example

.github/workflows/RELEASE.md, scripts/dev.sh
Relates to #1199
- update Release.md
- fix `dev.sh` didn't work correctly for scoped packages
=> chore: update release docs
