.github/workflows/release.yml
apps/docs/package.json

- Added conditiontional snapshot release to pipline
- we only want to publish a real version on the main branch
- all other branches/prs should only produce a snapshot
- Set `apps/docs` as private package as we don't want to publish it

chore: snapshot release for PRs

---

package.json
pnpm-lock.yaml

Installed `publint` as dependency to fix random pipeline failures.
The `npx publint` command downloads the `publint` package and runs it.
When it is run as a subcommand of `pnpm -r --parallel ` it creates a race-condition between the parallel sub-processes downloading, installing and running `publint`.
We can easily resolve this by installing `publint` as a dependency and then it even runs without the need for `npx`.

fix(check-code-quality): fix random publint failures

---

package.json
packages/sit-onyx/package.json
pnpm-lock.yaml

Removed `npm-run-all2` in order to minimize unnecessary dependencies.
`pnpm` already offers utilities for running multiple scripts: https://pnpm.io/cli/run#running-multiple-scripts
Therefore we have no need for `npm-run-all2` and can remove it and its sub-dependencies.

chore: remove redundant npm-run-all2

---

.github/workflows/deploy.yml

Env variables must be accessed via `vars.` instead of `env.`, see:
https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#environment-variables

chore: use env variables for deployment

---

packages/headless/package.json
packages/storybook-utils/package.json

Define missing `files` property of `package.json` that defines which files should be included when the package is released to npm

chore: define release files for headless and storybook-utils

---

.github/workflows/release.yml

We now make use of Githubs [Deploy Key](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/managing-deploy-keys#deploy-keys) Feature.
This allows us to configure pipelines to push with admin permissions and ignore branch protections.

fix(release): fix failing release pipeline caused by main branch being protected

---

apps/docs/package.json
apps/docs/src/.vitepress/theme/theme.scss
apps/docs/src/getting-started.md
apps/docs/src/packages/figma-utils.md
apps/docs/src/packages/headless.md
apps/docs/src/packages/storybook-utils.md
pnpm-lock.yaml

Update VitePress to add missing icon for external link, see [VitePress changelog](https://github.com/vuejs/vitepress/blob/main/CHANGELOG.md#100-rc36-2024-1-8).

docs: fix missing external link icons

---

apps/docs/package.json
packages/sit-onyx/package.json

Do not automatically open dev servers in the browser because for some browser (like Arc) that will open a redundant tab when new changes are saved (instead of re-loading the existing tab) which can get really annoying while e.g. writing documentation.

chore: do not auto open dev server in browser

---

apps/docs/src/getting-started.md
apps/docs/src/packages/figma-utils.md
apps/docs/src/packages/headless.md
apps/docs/src/packages/storybook-utils.md
apps/docs/src/packages/vitepress-theme.md

Update the docs to install our packages with the `@alpha` channel because we are currently in pre-release / alpha mode so trying to just install `sit-onyx` would always install version `0.0.0` although we already have e.g. version `1.0.0-alpha.1`

docs: use `@alpha` for installing packages

---

.github/dependabot.yml

Currently the dependabot opens a separate PR for every package which is way too much.
All updates will be grouped into 1 PR per week now.
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

chore(dependabot): group updates into single PR

---

package.json

Previously `build:all` only run the `build` script of every package which does not include storybook because it has a `build:storybook` script. This causes the deployment to fail.
Now `build:all` will run all scripts in every package that start with "build"

chore: also build storybook with `build:all` script

---

.changeset/brave-lobsters-wonder.md
packages/sit-onyx/src/i18n/index.ts

Ensure that the i18n instance is not reset when it has been provided.

fix(i18n): do not reset i18n when provided

---

apps/docs/src/.vitepress/components/DesignToken.vue
apps/docs/src/.vitepress/components/icons/CheckIcon.vue
apps/docs/src/.vitepress/components/icons/CopyIcon.vue

Add the design token component which is needed for #163, #159 and #160

docs: add DesignToken component

---

.changeset/nasty-mails-play.md
apps/docs/src/packages/vitepress-theme.md
packages/vitepress-theme/package.json
packages/vitepress-theme/src/mixins.scss

Add a scss mixin for applying CSS only to specific VitePress breakpoints

feat(vitepress-theme): add `breakpoint` scss mixin

---

packages/storybook-utils/src/actions.ts
packages/storybook-utils/src/types.ts

closes #166
Prevents build errors for `sit-onyx` with "cannot be named without a reference"

fix: prevent build error `cannot be named without a reference`

---

apps/docs/src/.vitepress/components/OnyxPartners.vue

Seems like VitePress does not support the `new URL()` syntax for image imports which is typically supported by Vite so we need to import every image explicitly.

docs: add missing images

---

apps/docs/src/.vitepress/components/OnyxRoadmap.vue
apps/docs/src/index.data.ts

Remove the contributors count from the docs because the GitHub API route seems to be flaky because it randomly fails in CI. Also the npm package count not ignores private packages like our eslint-plugin which is not published and should therefore not be included in the count.

docs: update facts and figures

---

apps/docs/src/.vitepress/config.ts

Highlight the nav items when a child of the nav section is currently active.

feat(docs): improve nav highlighting

---

.github/pull_request_template.md
.github/templates/playwright/action.yml
.github/workflows/check.yml
.github/workflows/release.yml

Update GitHub actions to use a node 20 based version instead of node 16 to prevent warnings in CI.

chore: update GitHub actions

---

apps/docs/src/.vitepress/components/TabGroup.vue

Prevent the tabs on the home page to be full width on a small breakpoint.

docs: fix tab mobile layout on home page

---

apps/docs/src/.vitepress/components/OnyxRoadmap.vue
apps/docs/src/.vitepress/config.ts
apps/docs/src/basics/colors.md
apps/docs/src/basics/infographics.md
apps/docs/src/basics/units.md
apps/docs/src/brand/changelog.md
apps/docs/src/brand/dependencies.md
apps/docs/src/brand/ideology.md
apps/docs/src/brand/index.md
apps/docs/src/brand/principles.md
apps/docs/src/brand/roadmap.md
apps/docs/src/resources/index.md
apps/docs/src/tokens/index.md

Remove empty/placeholder pages for now so we do not blow up our documentation with dummy content.

docs: remove empty pages

---

packages/sit-onyx/.storybook/docs-template.mdx

Previously, we used `<br>` inside our storybook docs template. Those added up to the margins of the text and bloated the layout.
In this PR, those `<br>`s are removed and the standard text is distincted from the component specfic information by making it italic.
**Before**
**After**

chore(docs): optimize storybook docs template

---

packages/sit-onyx/.eslintrc.cjs
packages/sit-onyx/package.json
packages/sit-onyx/src/components/TestInput/TestInput.vue
pnpm-lock.yaml

Add eslint plugin to disallow scoped and module CSS for components.
See [out Wiki](https://github.com/SchwarzIT/onyx/wiki/Technical-Vision-&-Guidelines#css) why we do this.

chore: add eslint plugin to prevent scoped CSS

---

packages/storybook-utils/src/preview.ts

The embedded Storybook component docs did not correctly switch to dark mode when the theme is toggled in VitePress.

docs: set Storybook dark mode correctly when switching VitePress theme

---

apps/docs/src/.vitepress/config.ts

closes #243 
Prevents an overflow of the nav content of our vitepress documentation by moving the "Report a Bug" and "Q&A" links into the "Resources" drop-down.

fix(docs): bundle top nav content

---

apps/docs/src/.vitepress/components/OnyxIconLibrary.vue
apps/docs/src/.vitepress/components/Search.vue
apps/docs/src/.vitepress/utils-icons.ts

Part of #242 
Implements a search functionality for our icon library documentation. Supports lower case search for icon name, icon alias and category name.

docs(icons): Implement search functionality in icon library

---

packages/sit-onyx/.storybook/docs-template.scss

Fix responsive overflow for the props/events table to be horizontally scrollable instead of overflowing the page width.
Before:
After:

docs: fix Storybook table overflow

---

apps/docs/src/.vitepress/components/ColorPalette.vue
apps/docs/src/.vitepress/components/ColorPaletteValue.vue
apps/docs/src/.vitepress/components/ComponentCard.vue
apps/docs/src/.vitepress/components/DesignToken.vue
apps/docs/src/.vitepress/components/DesignTokenCard.vue
apps/docs/src/.vitepress/components/HorizontalColorStripCard.vue
apps/docs/src/.vitepress/components/IconLibraryItem.vue
apps/docs/src/.vitepress/components/OnyxBorderRadiusTokens.vue
apps/docs/src/.vitepress/components/OnyxColorThemeDefinitions.vue
apps/docs/src/.vitepress/components/OnyxRoadmap.vue
apps/docs/src/.vitepress/components/OnyxSpacingTokens.vue
apps/docs/src/.vitepress/components/RoadmapCard.vue
apps/docs/src/.vitepress/components/Search.vue
packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.vue
packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.vue
packages/sit-onyx/src/styles/index.scss

closes #292
Replaced all occurrences of `1px` with the newly introduced CSS variable `--onyx-1px-in-rem`

refactor: replace 1px with css variable

---

.github/dependabot.yml
.github/workflows/check.yml
.github/workflows/import-figma.yml
.github/workflows/playwright-screenshots.yml
.github/workflows/release.yml

Update deprecated GitHub actions to remove warnings inside workflow runs.
Also updated dependabot to also check for GitHub action updates.

chore: update deprecated GitHub actions

---

.changeset/selfish-gifts-draw.md
packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.ct.tsx
packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.stories.ts
packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.vue
packages/sit-onyx/src/components/OnyxCheckbox/types.ts

#220
Make the label property required for accessibility / screen readers.
Add a new. `hideLabel` property to visually hide the label which will set the aria-label instead.

refactor(OnyxCheckbox): make `label` property required

---

.gitignore

Sometimes some temporary vitepress files are created, which will appear in `git status` and git UIs (like VS Codes Source Control).
This can be annoying and could be problematic if they are accidentally committed.

chore: gitignore temporary vitepress files

---

apps/docs/src/.vitepress/components/IconLibraryItem.vue

Update icon color to neutral-soft when not hovered/focussed to match the Figma design: https://www.figma.com/file/YfEUBOHk4J4nYrk04geswG/onyx---Design-System-Figma-Library?type=design&node-id=662-5755&mode=dev

docs(icon-library): update icon color

---

.changeset/short-grapes-reflect.md
packages/storybook-utils/package.json
pnpm-lock.yaml

sit-onyx uses a Storybook 8 beta based version while the storybook utils still ran on Storybook 7 which gave a runtime error on the deployed Storybook.

chore: fix deployed Storybook runtime error

---

.github/dependabot.yml

Temporary ignore Storybook updates because we use a canary release (see packages/sit-onyx/package.json)

chore(dependabot): temporary ignore Storybook updates

---

package.json
pnpm-lock.yaml

Update dependencies to fix our [current dependabot alert](https://github.com/SchwarzIT/onyx/security/dependabot/2) for a vulnerable dependency.

fix: remove vulnerable dependency

---

packages/sit-onyx/src/components/OnyxIcon/types.ts

closes #242
Adds an info about the onyx rem base to the icon size property.

docs(OnyxIcon): add rem base info

---

.github/dependabot.yml
packages/sit-onyx/.storybook/main.ts
packages/sit-onyx/package.json
packages/storybook-utils/package.json
pnpm-lock.yaml

Update to the regular Storybook 8 beta channel which not includes the Volar docgen plugin since beta 5,

chore: update to Storybook 8 beta

---

.changeset/angry-teachers-tickle.md
packages/storybook-utils/src/preview.ts

With this change browsers can render native elements like scrollbars in the selected theme. (light or dark)
Images show the difference:

feat: set browser color scheme depending on selected theme

---

packages/sit-onyx/playwright.config.ts

The [default GitHub runners](https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#standard-github-hosted-runners-for-public-repositories) have 4 CPU cores so can make use of them to speed up our workflows.
Previously we have limited Playwright to only use 1 core (which does not make sense).
The time for our current code check pipeline is reduced by 1 minute (25%).

perf: speed up playwright tests in CI

---

apps/docs/src/.vitepress/components/RoadmapCard.vue
packages/sit-onyx/src/components/OnyxLink/OnyxLink.stories.ts
packages/sit-onyx/src/components/OnyxLink/OnyxLink.vue
packages/sit-onyx/src/components/OnyxLink/types.ts

relates to https://github.com/SchwarzIT/onyx/issues/237#issuecomment-1978329032
Remove the noopener rel attribute when the link target is _blank since this is automatically done when noreferrer is set

refactor(OnyxLink): remove noopener from rel when link target is _blank

---

packages/sit-onyx/src/components/OnyxIconButton/OnyxIconButton.stories.ts
packages/sit-onyx/src/components/OnyxIconButton/OnyxIconButton.vue
packages/sit-onyx/src/components/OnyxIconButton/types.ts

Relates to #386 
Based on UX review:
- Change Story default icon to `trash`
- Restrict icon size to 24px

fix(OnyxIconButton): remove size prop

---

packages/sit-onyx/src/components/OnyxRadioButtonGroup/OnyxRadioButtonGroup.stories.ts

Relates to #364 
A single radio option inside a radio group can not be required.

docs: remove required option for truncated example

---

apps/alpha-test-app/src/style.css
apps/alpha-test-app/src/views/HomeView.vue
apps/alpha-test-app/src/views/LayoutDemoView.vue

Relates to #505 
Adds borders to the sidebar and nav bar placeholders of the alpha-test-app.

fix: add borders in alpha-test-app

---

apps/alpha-test-app/src/views/HomeView.vue

Relates to #567
- add OnyxTooltip to demo app
- support auto-complete for the component name when using the `show()` function for the demo page

docs: add OnyxTooltip to demo app

---

.changeset/sour-ties-impress.md
packages/chartjs-plugin/src/plugin.ts

Not all plugins might be registered/needed so we need to check that the plugin is registered before setting the default styles for it to prevent runtime errors.

fix: prevent errors for unregistered Chart.js plugins

---

apps/docs/src/development/packages/changelogs/[name].md

Add missing changelog for chartjs-plugin in our VitePress docs.

docs: add missing changelog for chartjs-plugin

---

apps/playground/src/components/TheHeader.vue
apps/playground/src/components/VersionSelect.vue

Relates to #704
Make playground header more responsive.
Old:
New:

fix(playground): optimize mobile header

---

.github/workflows/playwright.yml

Fix workflow condition when checking whether to update snapshots.
The final step is needed to we can set make the Playwright tests a required check in pull requests because we don't want to add each parallel matrix job individually.

chore: fix screenshot workflow

---

apps/alpha-test-app/src/views/HomeView.vue

Relates to #566
Add tag example to alpha demo app

docs: add tag example to alpha demo app

---

packages/sit-onyx/src/components/OnyxListbox/OnyxListbox.ct.tsx
packages/sit-onyx/src/components/OnyxListbox/OnyxListbox.vue
packages/sit-onyx/src/components/OnyxListbox/types.ts

Changed the prop type of `OnyxListbox` so that `modelValue`, `multiple` and `checkAll` directly depending on each other.
E.g., checking for `multiple === false` will also infer that `modelValue` is not an array and `checkAll` doesn't exist.

chore(OnyxListbox): make `multiple`, `modelValue` and `checkAll` types directly dependent on each other

---

.changeset/witty-houses-promise.md
packages/sit-onyx/src/components/OnyxCheckboxGroup/OnyxCheckboxGroup.stories.ts
packages/sit-onyx/src/composables/checkAll.ts

Closes to #1027 
Preserves the checked/unchecked state of disabled checkboxes in OnyxCheckboxGroup and OnyxListbox when using the "Check all" feature.
Reviewer info: test with
- http://localhost:6006/?path=/story/components-checkboxgroup--with-check-all
- http://localhost:6006/?path=/story/support-listbox--multiselect

fix: preserve disabled states when toggling "check all"

---

.changeset/loud-plants-deliver.md
packages/sit-onyx/src/components/OnyxNavItem/OnyxNavItem.vue

Relates to #
The OnyxNavItem only used opacity 0 when not hovered, so the nested children were still visible and clickable.

fix(OnyxNavItem): Hide nested children when navItem is closed

---

packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.stories.ts

Relates to #867
Add nav item with nested children to all Storybook examples

docs(nav-bar): add Storybook example with nested options

---

.changeset/afraid-avocados-hear.md
packages/chartjs-plugin/src/utils.ts

onyx has quantitative colors 100-1200 but currently we only supported 100-900 with no reason so I added 1000, 1100 and 1200 as well

feat: support quantitative colors 1000-1200 for `getDatasetColors()`

---

.github/workflows/check.yml

Currently when quickly pushing multiple commits to a PR, a new GitHub workflow run will be triggered so they all run in parallel and maybe need to wait for each other.
With this change, the previous run will be cancelled if a new commit is pushed
See the below screenshot where the previous run is canceled after I pushed a new commit:

chore: cancel previous GitHub workflows if PR is pushed

---

.github/workflows/check.yml
.github/workflows/release.yml
apps/docs/package.json
apps/docs/src/index.data.ts

Sometimes our GitHub action workflows for PRs fail due to a GitHub rate limit.
I changed it to skip the GitHub API during PR pipelines and only fetch it when deploying.

chore: fix GitHub rate limit in CI

---

.changeset/brave-owls-help.md
.changeset/pre.json
.gitignore
apps/docs/src/.vitepress/config.ts
apps/docs/src/development/index.md
apps/docs/src/development/packages/changelogs/[name].md
apps/docs/src/development/packages/nuxt.md
packages/nuxt/.gitignore
packages/nuxt/README.md
packages/nuxt/package.json
packages/nuxt/playground/app.vue
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/playground/package.json
packages/nuxt/playground/server/tsconfig.json
packages/nuxt/playground/tsconfig.json
packages/nuxt/src/module.ts
packages/nuxt/test/component-imports.test.ts
packages/nuxt/test/fixtures/basic/app.vue
packages/nuxt/test/fixtures/basic/nuxt.config.ts
packages/nuxt/test/fixtures/basic/package.json
packages/nuxt/tsconfig.json
packages/nuxt/vitest.config.ts
pnpm-lock.yaml

Relates to #1247
This PR adds a basic nuxt module to integrate onyx into nuxt projects. It just adds the global styles and auto imports all onyx components, more features may be added later.

feat: implement Nuxt module

---

.changeset/lovely-wasps-compete.md
.gitignore
packages/nuxt/src/module.ts

Building a nuxt project using the module would just hang up due to an issue within the postcss plugin "calc" used by nanocss which is used by nuxt's default postcss config.
This fix simply disables the plugin for nuxt projects using the module for now. An issue was created for the postcss plugin (see: https://github.com/postcss/postcss-calc/issues/210)
- [y] If a new component is added, at least one [Playwright screenshot test](https://github.com/SchwarzIT/onyx/actions/workflows/playwright-screenshots.yml) is added

fix(nuxt): disable postcss plugin calc to resolve issue caused by onyx using the calc-constant infinity

---

.changeset/light-lemons-cough.md
packages/nuxt/src/module.ts

Relates to #1261 
After fixing the build sadly the dev mode got broken by the postcss config. This PR fixes that by explicitly overwriting the cssnano config.

fix(nuxt): fix dev mode

---

.changeset/fuzzy-beds-worry.md
apps/docs/src/development/grid.md
packages/sit-onyx/src/index.ts

feat: Export info tooltip

---

.changeset/early-tools-melt.md
packages/storybook-utils/src/preview.spec.ts
packages/storybook-utils/src/preview.ts

Relates to #414
Automatically add imports for all used onyx components for the generated source code.

feat(storybook): add imports for onyx components in source code

---

packages/sit-onyx/src/components/OnyxBadge/OnyxBadge.stories.ts
packages/sit-onyx/src/components/OnyxButton/OnyxButton.stories.ts
packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.stories.ts
packages/sit-onyx/src/components/OnyxCheckboxGroup/OnyxCheckboxGroup.stories.ts
packages/sit-onyx/src/components/OnyxEmpty/OnyxEmpty.stories.ts
packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.stories.ts
packages/sit-onyx/src/components/OnyxRadioButtonGroup/OnyxRadioButtonGroup.stories.ts
packages/sit-onyx/src/components/OnyxSelectOption/OnyxSelectOption.stories.ts
packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.stories.ts
packages/sit-onyx/src/components/OnyxTable/OnyxTable.stories.ts
packages/sit-onyx/src/components/OnyxTag/OnyxTag.stories.ts
packages/sit-onyx/src/utils/storybook.ts

Relates to #1266
- Update truncation examples to use the `style` attribute instead of a Storybook decorator so it is included in the generated source code
- remove code duplication for the OnyxTable examples

docs: update truncation examples

---

apps/playground/src/App.vue
apps/playground/src/template/App.vue
packages/nuxt/README.md

Seems like the Playground does not support importing CSS files inside `<style>` so we need to import them in the preview options instead

docs(playground): fix missing global styles

---

.changeset/wise-owls-dance.md
packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.vue
packages/sit-onyx/src/composables/useResizeObserver.spec.ts
packages/sit-onyx/src/composables/useResizeObserver.ts

Relates to #1073 
Fix error when using the nav bar with Nuxt / server side rendering

fix(OnyxNavBar): support SSR

---

packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue

* added `scroll-padding-top` when search is enabled, so the scrollTo function considers the height of the sticky search

fix(OnyxSelect): fix item hidden beneath sticky search when using keyboard

---

apps/playground/src/template/App.vue

closes #1332
When opening the [onyx playground](https://playground.onyx.schwarz) the initial example shows a huge input.
I change it to a more subtle headline

docs(playground): update example code

---

apps/docs/src/.vitepress/config.ts
apps/docs/src/.vitepress/theme/TheLayout.vue
apps/docs/src/.vitepress/theme/index.ts

Relates to #1349
Provided custom footer with the original vitepress style.
A custom footer was necessary, as it is shown on every page.
The default footer was not shown on pages where the side-bar was opened.

chore(docs): Add imprint link to footer

---

apps/docs/.cloud-foundry/manifest-prod.yml
apps/playground/.cloud-foundry/manifest-prod.yml
packages/sit-onyx/.cloud-foundry/manifest-prod.yml

Increase instances count to two for increased failover, as recommended.
This also allows us to make use of the multiple geolocations of stackit.

Increase instances count to two for increased failover

---

apps/alpha-test-app/src/components/form-demo/FormDemo.vue
packages/sit-onyx/src/components/OnyxInput/OnyxInput.stories.ts
packages/sit-onyx/src/components/OnyxTextarea/OnyxTextarea.stories.ts

Relates to #1236
Gives space to the customError storybook examples so the tooltip won't be cut off.

fix: add space for storybook examples

---

packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.stories.ts
packages/sit-onyx/src/components/OnyxSelect/types.ts

Relates to #1266
Extend the description on `listLabel` of OnyxSelect.
Remove the duplicate `label` type declaration (it's already provided by `OnyxFormElementProps`).

docs (OnyxSelect): extend description on listLabel

---

.changeset/moody-kiwis-swim.md
.changeset/rotten-apricots-battle.md
packages/headless/src/composables/comboBox/createComboBox.ts
packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.ct.tsx

closes #1431
- do not submit form when pressing Enter

fix(OnyxSelect): do not submit form when pressing Enter

---

.changeset/curvy-mails-promise.md
packages/sit-onyx/src/components/OnyxAppLayout/OnyxAppLayout.stories.ts
packages/sit-onyx/src/components/OnyxPageLayout/OnyxPageLayout.stories.ts
packages/storybook-utils/src/source-code-generator.spec.ts
packages/storybook-utils/src/source-code-generator.ts

Merge latest changes of https://github.com/storybookjs/storybook/pull/27194.
Fixes code snippets when using slot bindings on a deployed Storybook

docs(storybook): fix code snippets for slot bindings

---

.changeset/nasty-planes-search.md
.changeset/old-dogs-sin.md
apps/docs/src/development/packages/nuxt.md
packages/nuxt/playground/nuxt.config.ts
packages/nuxt/src/module.ts
packages/nuxt/test/fixtures/i18n/nuxt.config.ts

This PR fixes an issue with the registration order warning of the nuxt module.
It also requires the user to specify a mapping for onyx locales to the locales from nuxt-i18n specific to their project.
This fixes a bug where all projects would display all locales of onyx as supported languages even if they were not specified within the project.
An issue and PR were already created for nuxt-i18n to support loading locales from npm packages. (https://github.com/nuxt-modules/i18n/issues/2999)
This way it would be possible to decouple onyx and nuxt-i18n while preserving easy support and customizability. This PR should make the onyx module useable until the feature is available inside nuxt-i18n.

fix(nuxt): require locale mapping for i18n integration

---

packages/sit-onyx/.storybook/theme-switch.ts

Relates to #764
The class for the default theme is `onyx-theme-default` but we are currently applying `onyx-theme-onyx` which does not work so the twogo theme is used as default currently because its the last registered theme

docs: fix default storybook theme

---

apps/docs/src/development/theming.data.ts
apps/docs/src/development/theming.md
packages/sit-onyx/.storybook/theme-switch.ts

Relates to #764
Currently our VitePress docs uses the twogo theme which is not correct. It should use the default onyx theme.
This is fixed in this PR. Also the Storybook theme switch now uses dynamic imports for the theme CSS styles

fix(docs): use correct theme for VitePress

---

packages/sit-onyx/.storybook/docs-template.mdx
packages/sit-onyx/.storybook/docs-template.scss
packages/sit-onyx/src/components/OnyxToast/OnyxToast.stories.ts

Relates to https://github.com/SchwarzIT/onyx/issues/1301#issuecomment-2219815724
- hide controls section in Storybook docs page when the component does not have any args/props (like the OnyxToast)
- add link to `createOnyx()` plugin for toast

docs(storybook): hide controls section if no arg table exists

---

.changeset/sour-birds-kneel.md
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxUserMenu/UserMenuLayout.vue

fix(OnyxUserMenu): hide mobile footer when it does not exist

fix(OnyxUserMenu): hide mobile footer when it does not exist

---

.changeset/thin-badgers-compare.md
packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.vue

Fix nav bar bottom bar to be full width when grid width is limited. Regression caused by #1566

fix(OnyxNavBar): make bottom border full width

---

.changeset/nice-clocks-kneel.md
apps/docs/src/.vitepress/components/ColorPalette.vue
packages/chartjs-plugin/src/utils.ts
packages/sit-onyx/package.json
packages/storybook-utils/src/theme.ts

We included the plain .ts files from the `src/types` folder because we used them in other packages like the storybook-utils.
But this causes build errors when used in projects because we import other types there which can not be resolved.
I removed the alias/mapping since we should not directly expose .ts files from our src folder in the build output.

fix: prevent "Cannot find module '../composables/density' or its corresponding type declarations." error

---

.github/dependabot.yml

Ignore major versions of `@types/node` for dependabot. We are using LTS node version which is currently 20 so we do not want to update the node types to the latest 22 (see #1648)

chore: ignore major `@types/node` update for dependabot

---

.changeset/empty-dingos-hug.md
packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue

closes #1146
According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-busy), `aria-busy` must only be used inside a `aria-live` region. Since the `OnyxSelect` has no live region, I removed the incorrect usage of the `aria-busy` attribute.

fix(OnyxSelect): remove incorrect usage of aria-busy

---

.github/workflows/playwright.yml

- We set [fail-fast](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstrategyfail-fast) to `false`, so that all shards run the tests to completion.
This way, we will have a full report at the end of the test run.
- Added comment explaining how to use the test-report

chore(CI): always run full test matrix, even when there are failing tests

---

.github/dependabot.yml

Follow up for #1681
Ignore updates for `@vue/repl` until the bug is fixed. We need it to be pinned to `4.2.1` for now.

chore: ignore `@vue/repl` in dependabot

---

.eslintrc.cjs
apps/demo-app/src/components/SelectDemo.vue
apps/playground/src/template/NewFile.vue
packages/nuxt/test/fixtures/i18n/pages/optional.vue
packages/nuxt/test/fixtures/i18n/pages/overwrite.vue
packages/nuxt/test/fixtures/i18n/pages/test.vue
packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.ct.tsx
packages/sit-onyx/src/components/examples/GridPlayground/GridPlayground.vue

While it is technical supported in Vue 3 to have multiple template roots, we want to prevent this since it can lead to unexpected issues when e.g. applying "class" or "style" attributes on such components

fix: enable eslint rule `vue/no-multiple-template-root`

---

packages/sit-onyx/tsconfig.app.json
packages/sit-onyx/tsconfig.node.json
packages/sit-onyx/tsconfig.playwright.json
packages/sit-onyx/tsconfig.vitest.json

Relates to #1668 
The incremental builds cause several errors (see below): Since we are using turbo repo which already caches the build, I don't think incremental builds deliver a real benefit to us.
- missing types when building multiple times: If building `sit-onyx` locally more than once, no types will be generated which causes build errors
- Running `pnpm build:all` or `pnpm build:all --force` in the monorepo fails

chore: disable incremental builds

---

.changeset/tricky-carrots-run.md
packages/vitepress-theme/package.json
packages/vitepress-theme/src/index.scss
packages/vitepress-theme/src/index.ts
pnpm-lock.yaml

Relates to #1709 
Looks like we are importing the fotns incorrectly in our vitepress theme because they are not recognized/applied when using the theme, see screenshot below. I also moved the font dependencies from peerDependencies to "regular" dependencies.

fix(vitepress-theme): correctly import fonts

---

.changeset/yellow-cameras-turn.md
packages/headless/src/utils/vitest.ts
packages/sit-onyx/src/composables/useResizeObserver.spec.ts
packages/sit-onyx/src/composables/useRipple.spec.ts
packages/sit-onyx/src/composables/useRipple.ts

Relates to #363
- fix "window.matchMedia is not a function" when using the `OnyxButton` in unit tests so projcets don't have to mock the function all the time
- remove 2 onyx internal unit test warnings

test: fix "window.matchMedia is not a function" error in unit tests

---

.changeset/fifty-students-turn.md
packages/sit-onyx/src/components/OnyxFormElement/OnyxFormElement.vue

The default value for the `id` prop of the `OnyxFormElement` was not unique. This was caused by calling `createId` only once.
Now `createId` is called for every component.

fix(OnyxFormElement): fix default id not unqiue

---

.github/workflows/import-figma-icons.yml
CODEOWNERS

Relates to #939
The automated requested UX reviewers for the icons did not work, see [this workflow run](https://github.com/SchwarzIT/onyx/actions/runs/10521665935). I added UX as codeowners instead so they are automatically requested for changes

chore: fix codeowners for icons

---

.github/workflows/check.yml
.github/workflows/release.yml

Relates to #1615
VitePress calculates the last updated date based on git.
However, our workflows only checked out the last commit so the real changed date of the individual markdown files was missing.
This is fixed now so every page shows the date when it was actually last updated.

fix(docs): show correct last updated timestamps on deployment

---

.changeset/sharp-rules-sing.md
packages/storybook-utils/src/actions.spec.ts
packages/storybook-utils/src/actions.ts

Relates to #1725
In #1725 we implemented auto actions for all component events. However, the actions/Events are logged with an "on" prefix, e.g. "onClick" instead of "click" although the "real" component event name is just "click" as it is defined with `defineEmits()`

fix(enhanceEventArgTypes): log actions/events without "on" prefix

---

.github/workflows/check.yml
.github/workflows/release.yml
packages/icons/package.json
packages/icons/scripts/changeset.spec.ts
packages/icons/scripts/changeset.ts
pnpm-lock.yaml

closes #1814
Fixes the issue that our icon library is not released when automated PRs for Figma imports are done.
Also fixes the issue that the documentation did not contain the latest changelogs when a release is done because it was build before the changelogs were generated.

chore: fix icon library release

---

.changeset/funny-spiders-help.md
packages/figma-utils/src/icons/parse.ts
packages/icons/src/metadata.json

Noticed in #1875 that currently empty strings are saved as aliases.

fix(icons): prevent empty string aliases

---

package.json
scripts/show-last-test-report.sh

This PR adds a neat little scrip `gh:show-report`, which uses the [GitHub CLI](https://cli.github.com/) and playwright to download and show the latest failed test report of the current branch.
GitHub CLI needs to be installed manually.

chore: add script for showing playwright report

---

packages/sit-onyx/tsconfig.node.json
packages/sit-onyx/tsconfig.playwright.json

In the local dev environment vite import features like queries (`import "xxx?raw"`) where marked with a typescript error:
> "Cannot find module 'xxx?raw' or its corresponding type declarations.ts(2307)"
This is now fixed by adding the `env.d.ts` declaration file to the includes of the `tsconfig.json` files used for local development.
Closes #1896

chore:  fix "Cannot find module" error in IDE when using vite specific import features

---

apps/docs/src/development/typography.md

- fix "yarn" script name to be yarn instead of pnpm
- document to install font families as direct dependencies instead if dev dependencies to match [font source install instructions](https://fontsource.org/fonts/source-sans-pro/install)

docs(typography): fix typo in code snippet

---

.changeset/pink-weeks-tan.md
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxMenuItem/OnyxMenuItem.stories.ts
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxMenuItem/OnyxMenuItem.vue
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxMenuItem/types.ts

relates to #1935
Support `target` property when OnyxMenuItem is used as link so it can be opened in a new tab.

feat(OnyxMenuItem): add property target

---

.changeset/beige-cherries-explain.md
packages/sit-onyx/src/components/OnyxButton/OnyxButton.ct.tsx
packages/sit-onyx/src/components/OnyxButton/OnyxButton.vue

closes #1934
Issue caused by #1902 
Fix OnyxButton to show ripple animation again on click.

fix(OnyxButton): ripple animation not working

---

packages/sit-onyx/.storybook/preview.ts
packages/sit-onyx/package.json
packages/sit-onyx/src/a11yConfig.ts
packages/sit-onyx/src/playwright/a11y.ts
packages/sit-onyx/tsconfig.node.json
pnpm-lock.yaml

Relates to #641 
Restrict a11y rules on Storybook

chore(storybook): Restrict a11y rules on Storybook

---

packages/sit-onyx/src/components/OnyxForm/OnyxForm.core.ts
packages/sit-onyx/src/components/OnyxForm/OnyxForm.stories.ts
packages/sit-onyx/src/components/OnyxForm/OnyxForm.vue
packages/sit-onyx/src/composables/useErrorClass.spec.ts
packages/sit-onyx/src/composables/useErrorClass.ts

Relates to #1375 
- improve storybook documentation for `OnyxForm`
- add defaults and specific control for `showError`
- rename `ShowErrorMode` type and add `ShowErrorModes` constant for type inference

chore(OnyxForm): improve storybook docs

---

.changeset/tender-foxes-burn.md
packages/sit-onyx/src/components/OnyxForm/OnyxForm.core.ts
packages/sit-onyx/src/composables/useManagedState.ts
packages/sit-onyx/src/composables/useSkeletonState.ts

Closes #1980
**Background:**
1. Vue Prop Runtime Validation Vue validates prop types at runtime (e.g., `typeof prop === "boolean"`). If a prop doesn't pass the validation, an error is logged (only in DEV mode): `Invalid prop: type check failed for prop "${name}". Expected ${expectedTypes}.`
1. Vue Prop Type inference Vue supports different ways to define the types of props, which are used for the runtime validation. We define the props using [type-based declaration](https://vuejs.org/guide/typescript/composition-api.html#typing-component-props). This means that the runtime types are inferred based on the typescript types.
**Cause:**
In our case, Vue's compiler inferred the prop type used for runtime validation as `Boolean`, even though the typescript type is `typeof unique symbol | …

fix: Fix uncaught TypeError for components with symbol props

---

.changeset/sixty-frogs-sneeze.md
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxNavButton/NavButtonLayout.vue
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxNavButton/OnyxNavButton.vue

closes #1965
Make property `mobileChildrenOpen` work again.
You can test it by changing line 66 in OnyxNavBar.stories.ts like this and then view to mobile nav bar:

fix(OnyxNavButton): prop mobileChildrenOpen not working

---

packages/sit-onyx/.storybook/vModel.ts

The filter logic of the `withOnyxVModelDecorator` was incorrect and never matched. This is fixed now by checking for the specific prop and checking its default value.

chore: fix `withOnyxVModelDecorator` storybook decorator never matching

---

.changeset/real-boxes-share.md
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxColorSchemeDialog/OnyxColorSchemeDialog.vue

Fix incorrect usage of `toRef` which causes the OnyxColorSchemeDialog and OnyxColorSchemeMenuItem to not work any more / not emit the selected color scheme.
As documented in the Vue docs, toRefs must not be used with props if the ref is modified (which is the case for us) since it would modify the prop directly which is invalid: https://vuejs.org/api/reactivity-utilities.html#toref

fix(OnyxColorSchemeDialog): fix warning "Set operation on key modelValue failed: target is readonly"

---

packages/sit-onyx/src/components/examples/ComponentShowcase/ComponentShowcase.vue

As found out in the review today, the navbar flyout is behind the headline underline of the general Storybook content in some browsers (e.g. Chrome).

docs(component-showcase): fix z-index issues

---

.changeset/little-avocados-breathe.md
packages/headless/src/composables/listbox/createListbox.ts
packages/headless/src/composables/tabs/TestTabs.ct.tsx
packages/headless/src/composables/tabs/TestTabs.vue
packages/headless/src/composables/tabs/createTabs.testing.ts
packages/headless/src/composables/tabs/createTabs.ts
packages/headless/src/index.ts
packages/headless/src/playwright.ts
packages/sit-onyx/src/components/OnyxFormElement/OnyxFormElement.vue
packages/sit-onyx/src/components/OnyxRadioGroup/OnyxRadioGroup.vue

Relates to #2018
Implement basic headless composable for [tabs](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/).

feat(headless): implement basic tabs composable

---

apps/demo-app/package.json
apps/docs/package.json
apps/playground/package.json
packages/chartjs-plugin/package.json
packages/nuxt/package.json
packages/sit-onyx/package.json
turbo.json

Relates to #1951 
Currently our dev scripts (e.g. of `sit-onyx`) do not work in a clean repository. The issue is that `sit-onyx` depends on other packages (like icons) to be build first.
I aligned all `dev` scripts for all packages to be run with turborepo so all dependencies are managed/build correctly.

chore: fix dev script of all packages to use turborepo

---

eslint.config.js
packages/sit-onyx/src/components/OnyxFormElement/TestWrapper.ct.vue
packages/sit-onyx/src/components/OnyxSelectInput/OnyxSelectInput.vue
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.vue
packages/sit-onyx/src/components/OnyxToast/OnyxToast.vue

Activate some more linting rules related to Vue block spacings white-spaces and newlines.

fix(lars-monk): enable linting Vue for block spacings

---

.changeset/tasty-baboons-impress.md
packages/shared/package.json
pnpm-lock.yaml

Fix dependency warning with a too strict version scope for `vue` and `sass-embedded` when a package is installed that depends on `@sit-onyx/shared` as peerDependency (e.g. `sit-onyx`).
We must not use `catalog:` for peerDependencies, otherwise it will require the exact dependency version to be installed in the project. This leads to install warnings when e.g.`sass-embedded` version `1.80.5` is required but `1.80.6` is installed

fix(@sit-onyx/shared): fix peerDependencies

---

apps/demo-app/src/components/SelectDemo.vue
apps/demo-app/src/components/form-demo/FormDemo.vue
apps/demo-app/src/components/layout-demo/BusyIndicatorDemo.vue
apps/demo-app/src/components/layout-demo/FlyoutDemo.vue
apps/demo-app/src/components/layout-demo/LayoutSettings.vue
apps/demo-app/src/components/layout-demo/MobileBottomFlyInDemo.vue
apps/demo-app/src/components/layout-demo/MobileNavFlyoutDemo.vue
apps/demo-app/src/components/layout-demo/NavBarDemo.vue
apps/demo-app/src/components/layout-demo/PageDemo.vue
apps/demo-app/src/components/layout-demo/SidebarDemo.vue
apps/demo-app/src/components/layout-demo/TempOverlayDemo.vue
apps/demo-app/src/views/DataGridView.vue
apps/demo-app/src/views/LayoutDemoView.vue
apps/docs/src/.vitepress/components/ColorPaletteValue.vue
apps/docs/src/.vitepress/components/DesignVariable.vue
apps/docs/src/.vitepress/components/DesignVariableBadge.vue
apps/docs/src/.vitepress/components/DesignVariableCard.vue
apps/docs/src/.vitepress/components/OnyxColorThemeDefinitions.vue
apps/docs/src/.vitepress/components/OnyxHomePage.vue
eslint.config.js
packages/headless/src/composables/comboBox/SelectOnlyCombobox.vue
packages/headless/src/composables/comboBox/createComboBox.ts
packages/headless/src/composables/menuButton/TestMenuButton.vue
packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/sorting.spec.ts
packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.vue
packages/sit-onyx/src/components/examples/GridPlayground/GridBadge/GridBadge.vue

We have some stricter general eslint rules that we are currently only applying to `sit-onyx` but not to other packages like custom Vue components in our docs.
We want to have a high code quality across all packages so I moved those general rules to be applied to the whole monorepo.

style(eslint): apply stricter general rules to all packages

---

apps/docs/src/.vitepress/components/DesignVariableCard.vue

Relates to #736 
Fix alignment for variable value when preview is high.
Before:
After:

docs(variables): fix card alignment

---

apps/docs/src/.vitepress/components/ColorPaletteValue.vue
apps/docs/src/.vitepress/components/ComponentCard.vue
apps/docs/src/.vitepress/components/ComponentRoadmap.vue
apps/docs/src/.vitepress/components/ComponentStatusBadge.vue
apps/docs/src/.vitepress/components/DensitySelection.vue
apps/docs/src/.vitepress/components/DesignVariable.vue
apps/docs/src/.vitepress/components/DesignVariableHeader.vue
apps/docs/src/.vitepress/components/IconLibraryItem.vue
apps/docs/src/.vitepress/components/OnyxHomePage.vue
apps/docs/src/.vitepress/components/OnyxIconLibrary.vue
apps/docs/src/.vitepress/components/OnyxTypography.vue
apps/docs/src/.vitepress/theme/TheLayout.vue
apps/docs/src/.vitepress/theme/index.ts
apps/docs/src/variables/spacings.md
apps/docs/tsconfig.json
apps/docs/vite.config.ts

We were currently using direct/relative imports for onyx components used in our VitePress docs. This required custom Vite/tsconfig options and might not be intuitive for new/External contributors taking a look at our codebase.
With our turbo repo setup, we can easily import directly from `sit-onyx` and turbo repo will make sure to build the components first. Like this our docs is just a regular consumer of the `sit-onyx` package, just like our playground and demo app.

refactor: remove relative onyx imports from docs

---

apps/docs/src/principles/contributing/testing-example.ct.tsx

Relates to #2169
We can import the densities so they do not have to be mainted manually

docs(contribution-guide): import densities

---

.github/workflows/check.yml
apps/docs/package.json
apps/docs/src/.vitepress/browser-loader.data.mock.ts
apps/docs/src/.vitepress/browser-loader.data.ts
apps/docs/src/github-api.ts

Fix flaky VitePress builds (esspecially in CI) by skipping all remote fetches in PR check pipelines.

docs: fix flaky VitePress builds

---

.changeset/itchy-ants-move.md
packages/sit-onyx/.storybook/preview.ts
packages/storybook-utils/src/preview.ts
packages/storybook-utils/src/theme.ts

We unintentionally introduced a breaking change in version `@sit-onyx/storybook-utils@1.0.0.beta.71` that forced the user to pass a required first parameter with brand details when calling `createPreview()`.
This was reverted now. The brand details are optional and can be passed as second parameter to `createPreview`.

fix(createPreview): revert unintentional breaking change

---

.github/workflows/check.yml
apps/docs/package.json
apps/docs/src/.vitepress/browser-loader.data.ts
apps/docs/src/cached.ts
apps/docs/src/github-api.ts

Cache vitepress requests in the node_modules folder for 24 hours.

feat: implement caching for vitepress fetch requests

---

.changeset/tame-wolves-push.md
packages/sit-onyx/.storybook/main.ts
packages/sit-onyx/src/components/OnyxMoreList/OnyxMoreList.stories.ts
packages/sit-onyx/src/components/OnyxMoreList/OnyxMoreList.vue
packages/sit-onyx/src/components/OnyxMoreList/TestWrapper.ct.vue
packages/sit-onyx/src/components/OnyxMoreList/types.ts
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxNavButton/OnyxNavButton.vue
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxNavSeparator/OnyxNavSeparator.vue
packages/sit-onyx/src/composables/useMoreList.ts
packages/sit-onyx/src/composables/useResizeObserver.spec.ts
packages/sit-onyx/src/composables/useResizeObserver.ts

Relates to #986
Implement more indicator for OnyxMoreList. For local testing, run Storybook and open:
http://localhost:6006/?path=/story/support-morelist--default

feat(OnyxMoreList): implement more indicator

---

.changeset/stupid-bottles-clap.md
packages/sit-onyx/src/components/OnyxDatePicker/OnyxDatePicker.ct.tsx
packages/sit-onyx/src/components/OnyxDatePicker/OnyxDatePicker.stories.ts
packages/sit-onyx/src/components/OnyxDatePicker/OnyxDatePicker.vue
packages/sit-onyx/src/components/OnyxDatePicker/types.ts
packages/sit-onyx/src/composables/useCustomValidity.spec.ts
packages/sit-onyx/src/composables/useCustomValidity.ts

Relates to #1818
Also fix the bug where the value is always `undefined`, when using `type="datetime-local"` by removing the usage of `valueAsDate` which does not work with date+time.

feat(OnyxDatePicker): implement `min` and `max` property

---

.changeset/spotty-dancers-jog.md
packages/sit-onyx/src/components/OnyxInput/OnyxInput.vue
packages/sit-onyx/src/components/OnyxSelectInput/OnyxSelectInput.vue
packages/sit-onyx/src/i18n/locales/de-DE.json
packages/sit-onyx/src/i18n/locales/en-US.json
packages/sit-onyx/src/styles/mixins/input.scss

PR feedback for #2143.
Changes:
- CSS implementation for show/hide clear and success icon when focused
- translate label for clear button
- make clear icon also accessible via keyboard + add focus styles
@ChristianBusshoff Please take a look :)

refactor(OnyxInput): use CSS implementation for clear and success icon

---

.github/templates/node-setup/action.yml

Looking at https://github.com/SchwarzIT/onyx/actions/runs/12179300264/job/33971147249 I noticed, that our cache command does not update:
> Post Run /./.github/templates/node-setup
> Post job cleanup.
> Post job cleanup.
> Cache hit occurred on the primary key Linux-caches, not saving cache.
> Post job cleanup.
> Cache hit occurred on the primary key node-cache-Linux-x64-pnpm-74339e7969f992363e9689a5a87f7851e81d1b5d2de2ff1763e6aad33ac19da7, not saving cache.
> Post job cleanup.
> Pruning is unnecessary.
This was caused by using a static caching key, buw now we include date and file hashes.

fix caching 

---

.changeset/real-bears-float.md

Relates to #1991
release version `1.0.0-beta.1` since #2269 only released `0.1.0-beta.0`
There are no changes in this version. We only bumped/fixed the package version to `1.0.0-beta.1` to be aligned with other packages.

chore: release playwright utils version `1.0.0-beta.1`

---

.changeset/six-buckets-doubt.md
packages/sit-onyx/src/components/OnyxSystemButton/OnyxSystemButton.vue
packages/sit-onyx/src/components/OnyxSystemButton/examples/WithFlyoutMenu.stories.ts
packages/sit-onyx/src/components/OnyxSystemButton/examples/WithFlyoutMenu.vue
packages/sit-onyx/src/components/OnyxSystemButton/examples/WithTooltip.stories.ts
packages/sit-onyx/src/components/OnyxSystemButton/examples/WithTooltip.vue

Relates to #2139
Add Storybook examples for using the OnyxSystemButton with a tooltip and a flyout menu.

docs(OnyxSystemButton): add tooltip and flyout menu example

---

packages/storybook-utils/src/preview.ts

If you load/reload the page in dark mode, switching to light mode is buggy.

fix: storybook dark mode to light mode toggle

---

.changeset/smart-tips-yell.md
packages/sit-onyx/src/styles/variables/density-compact.css
packages/sit-onyx/src/styles/variables/density-cozy.css
packages/sit-onyx/src/styles/variables/density-default.css
packages/sit-onyx/src/styles/variables/spacing.css
packages/sit-onyx/src/styles/variables/themes/digits-dark.css
packages/sit-onyx/src/styles/variables/themes/digits-light.css
packages/sit-onyx/src/styles/variables/themes/kaufland-dark.css
packages/sit-onyx/src/styles/variables/themes/kaufland-light.css
packages/sit-onyx/src/styles/variables/themes/lidl-dark.css
packages/sit-onyx/src/styles/variables/themes/lidl-light.css
packages/sit-onyx/src/styles/variables/themes/onyx-dark.css
packages/sit-onyx/src/styles/variables/themes/onyx-light.css
packages/sit-onyx/src/styles/variables/themes/schwarz-dark.css
packages/sit-onyx/src/styles/variables/themes/schwarz-light.css
packages/sit-onyx/src/styles/variables/themes/value.css

closes #2288
The schwarz-dark theme currently showed the wrong colors (onyx dark mode) because we used `:where(.dark)` as selector instead of `.dark` which was a leftover from a previous change.
I've run the Figma update variable workflow to update the theme correctly.

fix(schwarz-theme): use correct theme for dark mode

---

.github/templates/cf-push/action.yml
.github/templates/node-setup/action.yml
.github/workflows/check.yml
.github/workflows/deploy-turbo-remote-cache.yml
.github/workflows/import-figma-icons.yml
.github/workflows/import-figma.yml
.github/workflows/playwright-screenshots.yml
.github/workflows/playwright.yml
.github/workflows/release.yml
apps/turbo-remote-cache/.cloud-foundry/manifest-prod.yml
turbo.json

Closes #2321 
- Add deployment pipeline and CF manifest for [turborepo-remote-cache](https://ducktors.github.io/turborepo-remote-cache/)
- Remove GitHub pipeline caching of `.turbo` directories, only vitepress fetchs are cached now
- Configure all CI pipelines to make use of the remote turbo cache
- Add `varArgs` input to our GitHub `cf-push` custom action, which allows passing custom vars to be used in the manifest

fix(CI): fix CI caching, deploy and enable turbo remote cache

---

.changeset/breezy-cups-turn.md
packages/sit-onyx/src/components/OnyxInput/OnyxInput.vue

Relates to #2143 
As discussed with Jannick, the clear icon is no longer focusable via keyboard to not interrupt the users tab order when multiple form elements are used.

fix(OnyxInput): prevent keyboard focus on clear icon

---

.github/workflows/check.yml
.github/workflows/playwright.yml
apps/docs/package.json
apps/docs/playwright.config.ts
apps/docs/src/principles/contributing/index.md
apps/docs/src/principles/contributing/testing.md
apps/playground/package.json
apps/playground/playwright.config.ts
package.json
packages/chartjs-plugin/package.json
packages/chartjs-plugin/playwright.config.ts
packages/headless/package.json
packages/headless/playwright.config.ts
packages/shared/src/playwright.config.base.ts
packages/sit-onyx/package.json
packages/sit-onyx/playwright.config.ts
pnpm-lock.yaml
turbo.json

Relates to #2321
- Move build step as precondition for all checks and tests in the pipeline to create cache and avoid downstream build failures.
- Extracted shared playwright config into `@sit-onyx/shared` package as `PLAYWRIGHT_BASE_CONFIG` to reduce code duplications.
- Pass playwright shard configuration from `playwright.config.ts` file instead of using CLI arguments. See beneath for more details:
There was an issue where every shard executed a fresh build of all packages.
The cause was the `--shard` cli argument that differs for every shard.
Because [turbo considers](https://turbo.build/repo/docs/crafting-your-repository/caching#task-inputs) pass-through arguments in their hashing, there was always a hash mismatch.
Unfortunately, turbo doesn't support changing this behavior.
Luckily, …

chore: enable build caching for playwright tests

---

.changeset/ten-snakes-live.md
packages/sit-onyx/src/components/OnyxDialog/OnyxDialog.vue
packages/sit-onyx/src/components/OnyxMobileNavButton/OnyxMobileNavButton.vue
packages/sit-onyx/src/styles/root.scss
packages/sit-onyx/src/styles/variables/density-compact.css
packages/sit-onyx/src/styles/variables/density-cozy.css
packages/sit-onyx/src/styles/variables/density-default.css
packages/sit-onyx/src/styles/variables/spacing.css
packages/sit-onyx/src/styles/variables/themes/digits-dark.css
packages/sit-onyx/src/styles/variables/themes/digits-light.css
packages/sit-onyx/src/styles/variables/themes/kaufland-dark.css
packages/sit-onyx/src/styles/variables/themes/kaufland-light.css
packages/sit-onyx/src/styles/variables/themes/lidl-dark.css
packages/sit-onyx/src/styles/variables/themes/lidl-light.css
packages/sit-onyx/src/styles/variables/themes/onyx-dark.css
packages/sit-onyx/src/styles/variables/themes/onyx-light.css
packages/sit-onyx/src/styles/variables/themes/schwarz-dark.css
packages/sit-onyx/src/styles/variables/themes/schwarz-light.css
packages/sit-onyx/src/styles/variables/themes/value.css

closes #2229
In alignment with Jannick, we added a new variable in Figma for backdrops which contain the color + opacity in one single variable instead of having a dedicated numeric variable for the opacity.

feat: update CSS variables for backdrop

---

.changeset/ninety-spiders-return.md
packages/sit-onyx/src/i18n/index.ts

feat(i18n): Custom translation function can now be static

---

.github/workflows/check.yml

I would like to enable the GitHub [merge queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue) for our repository.
The benefit of the merge queue is that we no longer have to manually rebase our ready PRs from main every time there are updates on main because another PR was merged in the meantime. This slows down our workflow.
The GitHub merge queue will automate this by allowing us to add all ready PRs to the queue and will then update them one by one, ensure all required CI checks run successfully and merge them into main afterwards.

chore(CI): add `merge_group` trigger to check workflow

---

.changeset/good-hotels-brake.md
.changeset/red-candles-sin.md
packages/headless/src/composables/listbox/createListbox.ts

Relates to #2198
Fix scroll behavior to not scroll the whole page to the bottom of the screen if an option is selected.

fix(OnyxSelect): do not scroll whole page when opening with selected value

---

apps/docs/package.json
package.json
packages/sit-onyx/package.json
packages/storybook-utils/package.json
turbo.json

Relates to #2128
Implement PR feedback for stlylint PR #2128. Changes:
- run stylelint with turborepo to keep correct dependency build order
- add stylelint to more packages inside the monorepo
- use `**/*.css` glob to also include css files inside nested folders

refactor(stylelint): run with turbo

---

.changeset/unlucky-mice-ring.md
apps/demo-app/src/components/form-demo/FormDemo.vue
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.ct.tsx
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.stories.ts
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.vue
packages/sit-onyx/src/components/OnyxStepper/types.ts
packages/sit-onyx/src/components/examples/GridPlayground/EditGridElementDialog/EditGridElementDialog.vue
packages/sit-onyx/src/utils/numbers.spec.ts
packages/sit-onyx/src/utils/numbers.ts

PR review feedback/changes for #2416
Changes:
- update changeset
- update tests
- remove unused `step` and `stripStep` property as well as code to no longer modify the user entered value when `validStepSize` is set

implement PR review feedback for #2416

---

.changeset/hungry-mayflies-do.md
packages/sit-onyx/src/components/OnyxInfoTooltip/OnyxInfoTooltip.stories.ts
packages/sit-onyx/src/components/OnyxInfoTooltip/OnyxInfoTooltip.vue
packages/sit-onyx/src/components/OnyxInfoTooltip/types.ts

Allow passing all props of the OnyxTooltip to the OnyxInfoTooltip. Currently we limited the props which does not make sense

fix(OnyxInfoTooltip): add missing props from OnyxTooltip

---

.changeset/witty-geese-hope.md
packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.stories.ts
packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.vue
packages/sit-onyx/src/components/OnyxDataGrid/features/index.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/SortAction.vue
packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/sorting.ts
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/OnyxFlyoutMenu.vue
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxUserMenu/UserMenuLayout.vue
packages/sit-onyx/src/components/examples/DataGrid/SortingDataGrid.vue
packages/sit-onyx/src/i18n/locales/de-DE.json
packages/sit-onyx/src/i18n/locales/en-US.json

Relates to #2313
Implement menu items for sorting feature

feat(OnyxDataGrid): implement menuItems for sorting feature

---

.changeset/few-needles-double.md
packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.vue
packages/sit-onyx/src/components/OnyxCheckboxGroup/OnyxCheckboxGroup.vue
packages/sit-onyx/src/components/OnyxForm/FormElementTestWrapper.vue
packages/sit-onyx/src/components/OnyxForm/OnyxForm.core.spec-d.ts
packages/sit-onyx/src/components/OnyxForm/OnyxForm.ct.tsx
packages/sit-onyx/src/components/OnyxInput/OnyxInput.vue
packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.vue
packages/sit-onyx/src/components/OnyxRadioGroup/OnyxRadioGroup.vue
packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue
packages/sit-onyx/src/components/OnyxSelectInput/OnyxSelectInput.vue
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.vue
packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.vue
packages/sit-onyx/src/components/OnyxTextarea/OnyxTextarea.vue

Relates to #2308
Expose input elements of form elements, so that the native functions like `focus` or `select` can be used.

feat: expose internal inputs

---

.github/templates/node-setup/action.yml

Improved cache restore keys, as they only matched the same day.
If the day was different, the cache key didn't match anymore.
Also using `hashFiles` with the cache content doesn't make sense.

chore: improve cache restore keys

---

.changeset/seven-worms-happen.md
apps/docs/src/.vitepress/components/DesignVariableHeader.vue
apps/docs/src/.vitepress/components/OnyxIconLibrary.vue
packages/sit-onyx/src/components/OnyxHeadline/OnyxHeadline.vue
packages/sit-onyx/src/components/OnyxHeadline/types.ts
packages/sit-onyx/src/i18n/locales/de-DE.json
packages/sit-onyx/src/i18n/locales/en-US.json
packages/sit-onyx/src/index.ts
packages/sit-onyx/src/utils/strings.spec.ts

Relates to https://github.com/SchwarzIT/onyx/issues/569#issuecomment-2580111683
- hide `#` for screen readers
- add title and aria description
- automatically normalize hash so the user doesn't have to do this

feat(OnyxHeadline): automatically normalize hash

---

.changeset/empty-trees-scream.md
packages/sit-onyx/src/components/OnyxCheckbox/OnyxCheckbox.vue
packages/sit-onyx/src/components/OnyxCheckboxGroup/OnyxCheckboxGroup.vue
packages/sit-onyx/src/components/OnyxDatePicker/OnyxDatePicker.vue
packages/sit-onyx/src/components/OnyxInput/OnyxInput.vue
packages/sit-onyx/src/components/OnyxRadioButton/OnyxRadioButton.vue
packages/sit-onyx/src/components/OnyxRadioGroup/OnyxRadioGroup.vue
packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue
packages/sit-onyx/src/components/OnyxSelectInput/OnyxSelectInput.vue
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.vue
packages/sit-onyx/src/components/OnyxSwitch/OnyxSwitch.vue
packages/sit-onyx/src/components/OnyxTextarea/OnyxTextarea.vue

closes #2554
As described in #2554, the issue should already be fixed in Vue version 3.5.2. However, this does not seem to be the case. I assume this might be because we are building the `sit-onyx` library (prod mode) and then use it in an application (dev mode). Vue might handle prod and dev mode differently.
As temporary fix for our onyx users, I renamed the template refs to be different from the variable name.
I also created follow up tickets:
- #2556
- #2557
You can verify the fix by running the demo app and check the console.

fix console warning for form elements about readonly target

---

.changeset/strange-teachers-hope.md
packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.stories.ts
packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.vue
packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGridRenderer/OnyxDataGridRenderer.vue

Added empty slot to DataGrid to be able to pass custom empty content

feat(DataGrid): add empty state slot

---

.changeset/giant-camels-judge.md
.changeset/rotten-scissors-remember.md
packages/shared/package.json
packages/sit-onyx/src/index.ts
pnpm-lock.yaml

When installing the latest onyx version in a project that uses Vite 5, it will show a peerDependency mismatch warning since `@sit-onyx/shared` is declared to required Vite 6. However, the vite dependencies are only needed when importing the shared vite config which is mainly done inside our monorepo.
I changed the dependencies to be optionalDependencies to get rid of the warning.

fix(shared): change vite dependencies to optionalDependencies

---

packages/sit-onyx/src/components/OnyxAlertDialog/OnyxAlertDialog.stories.ts
packages/sit-onyx/src/components/OnyxModalDialog/OnyxModalDialog.stories.ts
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxColorSchemeDialog/OnyxColorSchemeDialog.stories.ts

Relates to https://github.com/SchwarzIT/onyx/issues/2384#issuecomment-2611865738
Currently, when setting the `open` property manually, the close button did not close the dialog again.

docs(OnyxColorSchemeDialog): fix Storybook example when open property is set manually

---

.github/workflows/playwright-screenshots.yml
apps/demo-app/package.json
apps/docs/package.json
apps/docs/src/principles/contributing/index.md
apps/playground/package.json
package.json
packages/chartjs-plugin/package.json
packages/nuxt/package.json
packages/sit-onyx/package.json
scripts/dev.sh
scripts/show-last-test-report.sh
turbo.json

- **use turbo watch command for development:**
Finally figured out how to use `turbo watch` correctly.
It only works from the root of the project.
Added a small helper script to let you start the dev mode more easily.
Updated relevant docs. Removed now redundant `turbo:dev` npm scripts.
- **updated shell scripts to print commands and exit on first error**

chore: use turbo watch command for development

---

.changeset/old-rocks-tickle.md
packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue

- added: transition between open and close state 
minimal effort by using experimental features supported by chrome and edge
afaik should not cause any problems in firefox, but of course no animation there then

feat(OnyxAccordionItem): transition between open and close state

---

.changeset/lazy-pumpkins-develop.md
packages/sit-onyx/src/components/OnyxExternalLinkIcon/OnyxExternalLinkIcon.vue
packages/sit-onyx/src/composables/useLink.ts
packages/sit-onyx/src/utils/index.spec.ts
packages/sit-onyx/src/utils/index.ts

Relates to #447 
Fix detection of external links. Since there are way more variations for external than for internal links, we will just detect if the link is internal and treat all other links as external.
Previously only links starting with `http://` or `https://` we detected as external links, meaning all other links we treated as internal and navigated using the [provided Vue Router](https://onyx.schwarz/development/router.html).
Since this is incorrect for links like `mailto:`, `tel:` etc. this behavior has been fixed.
Now only links starting with `/` and `#` are treated as **internal**. All other links are treated as **external**.

fix: correctly detect links as external

---

.github/ISSUE_TEMPLATE/98-dev-story.yml
packages/sit-onyx/.storybook/main.ts
packages/sit-onyx/.storybook/manager.ts
packages/sit-onyx/package.json
packages/sit-onyx/src/components/OnyxAccordion/OnyxAccordion.stories.ts
packages/sit-onyx/src/components/OnyxButton/OnyxButton.stories.ts
packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.stories.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/selection/selection.stories.ts
packages/sit-onyx/src/components/OnyxIconButton/OnyxIconButton.stories.ts
packages/sit-onyx/src/components/OnyxSystemButton/OnyxSystemButton.stories.ts
pnpm-lock.yaml

Relates to #2369
Configure Storybook addon to show "new" badges for new components and features.

docs: show `new` badges for new components and features

---

package.json
packages/sit-onyx/src/components/OnyxButton/OnyxButton.ct.tsx
packages/sit-onyx/src/components/OnyxIconButton/OnyxIconButton.ct.tsx
packages/sit-onyx/src/components/OnyxSystemButton/OnyxSystemButton.ct.tsx

Relates to #1947
Add Playwright tests for link buttons

test: add Playwright tests for link buttons

---

apps/turbo-remote-cache/.cloud-foundry/manifest-prod.yml

Even when running our tests (with 12 shards loading from the cache) we barely use 30% of the assigned memory:
So we should be able to reduce the cost and memory assigned by 50%.

chore: Reduce resources for turbo remote cache

---

.changeset/tall-carrots-flash.md
packages/sit-onyx/package.json
packages/sit-onyx/src/i18n/index.spec.ts
packages/sit-onyx/src/i18n/index.ts
packages/sit-onyx/src/i18n/locales/de-DE.json
packages/sit-onyx/src/i18n/locales/en-US.json
pnpm-lock.yaml

Currently the `<OnyxInput type="email" />` will crash/throw an error if the error message is shown when used inside Nuxt.
This is caused because in our Nuxt module, the `t` function from vue-i18n is used instead of our onyx t function.
Because in vue-i18n, some characters needs to be escaped (like `@`).
I updated the onyx i18n implementation to escape those characters and also added unit tests to ensure that all onyx messages can be compiled without errors with vue-i18n

fix(i18n): prevent message compilation error in Nuxt

---

.github/ISSUE_TEMPLATE/01-bug_report.yml
.github/ISSUE_TEMPLATE/02-feature_request.yml

We switched from labels to the new `type` field for bugs.

chore: update issue templates to use type field

---

.changeset/cold-pugs-push.md
packages/sit-onyx/src/components/OnyxAccordionItem/OnyxAccordionItem.vue

fix(OnyxAccordionItem): fix open indicator displaying parent state instead of their own

---

.changeset/great-cameras-give.md
packages/sit-onyx/src/components/OnyxDataGrid/examples/CustomFeatureExample.vue
packages/sit-onyx/src/components/OnyxDataGrid/examples/DefaultExample.vue
packages/sit-onyx/src/components/OnyxDataGrid/examples/FilteringExample.vue
packages/sit-onyx/src/components/OnyxDataGrid/examples/SelectionExample.vue
packages/sit-onyx/src/components/OnyxDataGrid/examples/SortingExample.vue
packages/sit-onyx/src/components/OnyxDataGrid/features/index.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/renderer.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/renderers.spec.ts

Relates to #2815
Support new default supported data grid column types:
| Type      | Example output              |
| --------- | --------------------------- |
| date      | Mar 11, 2025                |
| datetime  | Mar 11, 2025, 9:51 AM       |
| time      | 9:51 AM                     |
| timestamp | 03/11/2025, 09:51:27 AM GMT |

feat(OnyxDataGrid): support column type `date`, `datetime-local`, `time` and `timestamp`

---

.changeset/real-garlics-return.md
packages/sit-onyx/src/components/OnyxSelect/OnyxSelect.vue

Currently when passing `<OnyxSelect :multiple="false" />` a type error is throwns because only true and undefined are accepted.

fix(OnyxSelect): accept `:multiple="false"` without type errors

---

.changeset/lazy-pianos-flash.md
apps/demo-app/src/views/DataGridView.vue
packages/sit-onyx/src/components/OnyxDataGrid/examples/ResizingExample.vue
packages/sit-onyx/src/components/OnyxDataGrid/features/resizing/resizing.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/resizing/types.ts

Relates to #2502, https://github.com/SchwarzIT/onyx/issues/2502#issuecomment-2732071767
Align the enabled API with all other data grid features

refactor(OnyxDataGrid): align enabled options for useResizing

---

packages/sit-onyx/src/utils/attrs.spec.ts
packages/sit-onyx/src/utils/attrs.ts

This addresses the issue of refs to from an element being needed by multiple `v-bind` attributes sources.
The default `mergeProps` behaviour will just overwrite the `ref` if it is defined multiple times.
This also the case when using `ref` on a an elment and a ref defined via v-bind: [Playground example](https://play.vuejs.org/#eNp9UrFuwjAU/BXLCyDRMLQTDUhtxdAObUU7egnhJYQ6tmW/BKQo/95np0mDhNjsu3v37mQ3/MmYqK6AL3nsUlsYZA6wMmuhitJoi6xhpwTTwybLIEXWsszqkk1oZPI40ljILjihhEq1csgQSiMThC0pVl43nfXUrlD7K3CCaB2BwXU5qFrvOcoync7Yas38jJYQSZ1PR7uiOpEVzPvp7jqjHfGi60kN6dJP0I2xuFCmQr91JfjIS3BW33kjgkM4AhbreGfD1Ei4ZE1zUbhtWS/7CxIkQ6WejhejIHzO0VGtrMijo9OK3qbxDoKnujSFBPthsKDagpObZzyXSKlPbwFDS817PD1A+nMFP7qzxwT/tODA1iD4wGFic8CO3ny9w5nOA1nqfSVJfYPcAj1J5TN2sudK7Sn2SBfSvobfU6j8223OCMr1pXxQr2yDXnD6US83qv/HvY8ewpxQLW9/Af …

internal: update `mergeVueProps` to support merging of vnode refs

---

.changeset/rude-bikes-strive.md
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/OnyxFlyoutMenu.ct.tsx
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/OnyxFlyoutMenu.vue
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/TestWrapperMany.ct.vue

Relates to #2890 
- Limites the mumber of visible menu items in the `OnyxFlyoutMenu` to 8, as defined in Figma.
- added tests for this behavior
- added test for hover behavior

fix(OnyxFlyoutMenu): fix max-height and scrollable behavior for OnyxFlyoutMenu

---

.changeset/silent-bags-sing.md
packages/sit-onyx/src/components/OnyxDataGrid/features/filtering/filtering.ts
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/OnyxFlyoutMenu.ct.tsx
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/OnyxFlyoutMenu.vue
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/TestWrapper.ct.vue

Closes #2888 
- `OnyxColorSchemeDialog` is a child element of `OnyxColorSchemeMenuItem`, which is teleported to the body
- `OnyxFlyoutMenu` renders `menuitem`s when it's opened (e.g. by hovering its button)
- Clicking a `menuitem` closes the `OnyxFlyoutMenu` and unmounts its `menuitem`s
- This way the parent of `OnyxColorSchemeDialog` was unmounted and therefore the dialog was unmounted, too.
- Replace `v-if` with `v-show` for the `menuitems` in the `OnyxFlyoutMenu`, so that `OnyxColorSchemeMenuItem` is only visually hidden and not unmounted
- This way `OnyxColorSchemeDialog` will be shown, because its parent still exists
- This has the unfortunate side-effect, that the `autofocus` inside of the flyout will not work (it only works on inital render)
- This affects the FlyoutMenu inside the …

fix(OnyxColorSchemeMenuItem): fix not opening OnyxColorSchemeDialog on click

---

packages/sit-onyx/src/components/OnyxDataGrid/features/index.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/renderer.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/renderers.spec.ts
packages/sit-onyx/src/i18n/datetime-formats.ts
packages/sit-onyx/src/i18n/index.spec.ts
packages/sit-onyx/src/i18n/index.ts
packages/sit-onyx/src/i18n/number-formats.ts

Support unified date and number formats so they can be reused across all components.
This is extracted from #2960.
The API is aligned with [vue-i18n](https://vue-i18n.intlify.dev/guide/essentials/datetime.html)

refactor(i18n): create reusable date and number formats

---

packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.stories.ts
packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.vue
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxNavItem/OnyxNavItem.stories.ts
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxNavItemFacade/OnyxNavItemFacade.vue

Relates to #2171 
- Updated NavBar story example and documentation
- fix `focus` state of `OnyxNavItem`

docs(OnyxNavBar): updated storybook

---

packages/sit-onyx/src/components/OnyxDataGrid/OnyxDataGrid.stories.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/hideColumns/hideColumns.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/index.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/selection/selection.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/sorting/sorting.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/stickyColumns/stickyColumns.ts
packages/sit-onyx/src/utils/storybook.ts

some minor changes:
- column `label` is now resolved as part of the normalization
- `header.actions` now uses the available `InternalColumnConfig` type instead of the less accurate `PublicNormalizedColumnConfig`
- OnyxDataGrid: The column label is now used instead of the key for the sorting buttons

fix(OnyxDataGrid): fix sorting buttons of `useSorting` feature using column key instead of label 

---

.github/ISSUE_TEMPLATE/01-bug_report.yml
.github/ISSUE_TEMPLATE/02-feature_request.yml

I updated the issue template, so that
- now it's automatically also added to our project and it's backlog
- the issues are labeled with `needs-triage`, so that we know that it is an external request and we need to analyze it

chore: update issue template

---

.changeset/few-knives-admire.md
packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.ct.tsx
packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.stories.ts
packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.vue
packages/sit-onyx/src/components/OnyxNavBar/TestCase.vue
packages/sit-onyx/src/components/OnyxNavBar/types.ts

Relates to #2228 
- rename prop `mobileBreakpoint` to `mobile`: behaves as before, but also supports boolean type
- renamed so the naming matches the new behaviour better

feat(OnyxNavBar): update mobileBreakpoint prop

---

.changeset/chatty-clubs-hang.md
packages/sit-onyx/src/composables/useCustomValidity.spec.ts
packages/sit-onyx/src/composables/useCustomValidity.ts

Closes #3226 
**Cause:**
- the `validityState` setter logic depends on `setCustomValidity` to have been executed beforehand
- `setCustomValidity` and `validityState` would sometimes be out-of-sync, because they were called in separate watchers
**Fix:**
- The setter logic for the `validityState` now also calls `setCustomValidity`
- Additionally we now use "post" flush timing, to ensure the DOM is up-to-date and the elements validity state is in sync. This might cause an additional render-cycle in some cases.

fix(useCustomValidity): fix sometimes missing error message

---

.changeset/metal-mice-unite.md
packages/shared/src/breakpoints.ts

closes #3290
Fix console warning for OnyxNavBar `mobile` property

fix(OnyxNavBar): prevent console warning for invalid `mobile` property

---

.changeset/blue-seas-watch.md
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/OnyxFlyoutMenu.vue
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxFlyoutMenu/types.ts

The type of the `alignment` property of the OnyxFlyoutMenu was invalid because of an invalid import of the type.
This lead to a bug that the property was considered required and did not gave type information.

fix(OnyxFlyoutMenu): fix `alignment` property type and make it optional

---

.github/workflows/check.yml
package.json

Relates to #2940
- fix vitest coverage directory for github coverage upload
- ignore suppressed (disabled) eslint warnings in sarif report, so that github and sonarqube do not complain about them also

chore: ignore suppressed eslint rules in sarif report

---

apps/docs/src/flags.md

Relates to #2701
Add docs for how to get the country name of a flag

docs(flags): add docs for country names

---

packages/sit-onyx/src/components/OnyxDataGrid/examples/CustomColumnTypes.vue
packages/sit-onyx/src/components/OnyxDataGrid/examples/DefaultExample.vue

Relates to #2783 
- added usage example for `createTypeRenderer`
- added example for base type renderer options

chore: add typerenderer custom option Story example

---

.changeset/good-oranges-heal.md
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.ct.tsx
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.vue
packages/sit-onyx/src/utils/numbers.spec.ts
packages/sit-onyx/src/utils/numbers.ts

closes #3389
Fix current stepper bug where 0 is not correctly formatted when used with precision

fix(OnyxStepper): correctly format 0 when used with precision

---

packages/sit-onyx/.storybook/pages/illustrations.mdx

Fix the current [about illustrations](https://storybook.onyx.schwarz/?path=/docs/illustrations-about-illustrations--docs) Storybook page due to a missing import.

docs: fix broken "About illustrations" page

---

.changeset/tall-jokes-relax.md
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxTimer/OnyxTimer.vue
packages/sit-onyx/src/composables/useTimer.ts

closes #3518
Expose internal `timeLeft` (and make it readonly) so the project can use it for custom logic (e.g. do some action 30 seconds before the timer expires).

feat(OnyxTimer): expose `timeLeft`

---

.changeset/polite-bags-send.md
packages/sit-onyx/src/components/OnyxForm/OnyxForm.core.spec-d.ts
packages/sit-onyx/src/composables/useLink.spec-d.ts
packages/sit-onyx/src/composables/useLink.spec.ts
packages/sit-onyx/src/composables/useLink.ts

Relates to #3450
Also consider hashes when determining the active state of a link when a Vue Router is provided. E.g. the link `#some-headline` will now be active when the current route is `/page-1#some-headline`

feat(router): consider hash for active state

---

.changeset/twelve-impalas-create.md
packages/sit-onyx/src/components/OnyxProgressSteps/OnyxProgressSteps.stories.ts
packages/sit-onyx/src/components/OnyxProgressSteps/examples/DefaultExample.vue
packages/sit-onyx/src/components/OnyxProgressSteps/examples/SkeletonExample.vue
packages/sit-onyx/src/components/OnyxProgressSteps/examples/VerticalExample.vue
packages/storybook-utils/src/preview.ts
packages/storybook-utils/src/theme.ts

- fix(storybook-utils): fix viewports not applied correctly
- remove custom type `StorybookBreakpoint` in favor of official Storybook type
- update OnyxProgressSteps code examples

fix(storybook-utils): configure onyx viewports options correctly

---

.changeset/common-otters-leave.md
packages/sit-onyx/src/components/OnyxMiniSearch/OnyxMiniSearch.vue

The text color of the OnxyMiniSearch was not set correctly so it was very dark in dark mode which had very low contrast.

fix(OnyxMiniSearch): fix text color with filled value in dark mode

---

packages/sit-onyx/src/components/examples/NotificationCenter/NotificationCenter.stories.ts
packages/sit-onyx/src/components/examples/NotificationCenter/NotificationCenter.vue
packages/sit-onyx/src/index.ts
packages/sit-onyx/src/utils/storybook.ts

Due to the change of pure ESM package, our Storybook code snippets are currently not showing the correct import paths from "sit-onyx"

docs: fix import path in code snippets

---

.changeset/light-mirrors-jump.md
packages/sit-onyx/src/components/OnyxTextarea/OnyxTextarea.ct.tsx
packages/sit-onyx/src/components/OnyxTextarea/OnyxTextarea.vue

Closes #3797
Cause: We use a invisible pseudo element which duplicates the input text as reference element to determine the wanted textarea height (Because replaced elements are weird). The pseudo element had a `max-height`, but text can grow outside anyways, which caused the page height grow.
Fix: Add an `overflow-y` restriction.

fix(OnyxTextarea): fix invisible overflow

---

.changeset/lazy-llamas-lose.md
packages/figma-utils/src/commands/import-variables.ts
packages/sit-onyx/src/styles/variables/density-compact.css
packages/sit-onyx/src/styles/variables/density-cozy.css
packages/sit-onyx/src/styles/variables/density-default.css
packages/sit-onyx/src/styles/variables/spacing.css
packages/sit-onyx/src/styles/variables/themes/onyx.css
packages/sit-onyx/src/styles/variables/themes/value.css

Relates to #3650
The base theme name was not determined correctly, e.g. "schwarzgroup-scos-light" was set to "schwarzgroup" only instead of "schwarzgroup-scos"

fix(import-variables): correctly get theme name when combinesDarkLight is enabled

---

apps/docs/src/development/theming.md

Relates to #3650
Update docs to rename the scos theme to schwarz group + scos

docs: rename scos theme to schwarz group and scos

---

.changeset/petite-waves-cut.md
.changeset/wild-forks-burn.md
packages/flags/package.json
packages/icons/package.json
packages/storybook-utils/src/preview.spec.ts
packages/storybook-utils/src/preview.ts

closes #3836
relates to #1802
The usage of "getIconImportName" in our Storybook utils seemed to break the deployed Storybook (see #1802). Weirdly, the utility works totally fine when used with Vitest or in our documentation.
Regardlessly, we want to update the Storybook utils anyways in #3836 to use the new JavaScript imports for the code snippets instead of raw SVG imports. This was implemented in this PR so the "getIconImportName" utility is no longer needed and therefore the deployed Storybook works fine again.

feat: update onyx icon code replacement to use JavaScript instead of raw SVG imports

---

.changeset/bitter-paths-run.md
packages/nuxt-docs/package.json

Relates to #3800 
After the release of #3800, I noticed that the Nuxt docs layer does not work at all when used inside a project.
The reason is that due to the Nuxt 4 migration, all relevant files are now placed inside the "app" directory but our "files" definition in package.json did not include the directory when publishing so the file were missing in the npm package.

fix(nuxt-docs): correctly pack files when publishing

---

.changeset/social-terms-look.md
.changeset/thick-cows-fetch.md
.changeset/tidy-lights-drive.md
apps/docs/src/.vitepress/components/AssetLibrary.vue
apps/docs/src/.vitepress/components/OnyxFlagLibrary.vue
apps/docs/src/.vitepress/components/OnyxIconLibrary.vue
apps/docs/src/flags.md
apps/docs/src/icons.md
packages/flags/src/utils.ts
packages/flags/vite.config.ts
packages/icons/src/utils.ts
packages/icons/vite.config.ts
packages/sit-onyx/.storybook/main.ts
packages/sit-onyx/src/components/OnyxIcon/OnyxIcon.stories.ts
packages/storybook-utils/package.json
packages/storybook-utils/src/preview.spec.ts
packages/storybook-utils/src/preview.ts
packages/vite-plugin-svg/src/index.ts
packages/vite-plugin-svg/src/utils.ts
pnpm-lock.yaml

Relates to #1802
- update icon and flag docs to mention the new JavaScript imports
- update Storybook utils to also support replacing flag imports in the source code snippets (can be tested on http://localhost:6006/?path=/docs/navigation-navbar-modules-colorschememenuitem--docs)

feat: update docs and Storybook utils for icons and flags

---

.changeset/whole-glasses-stare.md
packages/icons/src/index.ts
packages/vite-plugin-svg/src/index.ts

Relates to #3938
Cause: The typescript definition file was created with the name `virtual:vite-plugin-svg.d.ts`. 
But `:` is a [reserved character on Windows](https://learn.microsoft.com/en-us/windows/win32/fileio/naming-a-file#naming-conventions), which causes issues with the module resolution on that OS.
Fix: We now use a file name without any special characters.

fix(@sit-onyx/vite-plugin-svg): Failing module resolution on Windows systems

---

.changeset/forty-dogs-stand.md
packages/sit-onyx/CHANGELOG.md

I received feedback that the changelog for version 1.0.0-beta.290 is incorrect because it documents to use `$event && onClose` although it should be `!$event && onClose`

docs: fix changelog for version `1.0.0-beta.290`

---

.changeset/good-webs-serve.md
packages/sit-onyx/CHANGELOG.md

Currently the [release pipeline](https://github.com/SchwarzIT/onyx/actions/runs/17149340258) is failing because the docs can not be build due to an invalid changelog.
The changelog is fixed with this PR.

docs: fix build due to invalid changelog

---

.changeset/evil-masks-sip.md
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.ct.tsx
packages/sit-onyx/src/components/OnyxStepper/OnyxStepper.vue

Relates to #3898
- When a number is removed, NaN is displayed.

bug(Stepper): handle NaN in displayValue

---

.github/workflows/release.yml

The [last demo app deployment ](https://github.com/SchwarzIT/onyx/actions/runs/17318053222/job/49164803663)failed because the build artifact could not be found
The artifact upload action excludes hidden files by default. Since the ".output" folder starts with a dot, it is considered a hidden file so we need to explicitly allow it

chore: fix missing artifact during demo app deployment

---

.changeset/fair-cooks-unite.md
.changeset/few-ears-peel.md
packages/sit-onyx/src/components/OnyxMoreList/OnyxMoreList.ct.tsx
packages/sit-onyx/src/components/OnyxMoreList/OnyxMoreList.stories.ts
packages/sit-onyx/src/components/OnyxMoreList/OnyxMoreList.vue
packages/sit-onyx/src/components/OnyxMoreList/TestChild.vue
packages/sit-onyx/src/components/OnyxMoreList/TestWrapper.ct.vue
packages/sit-onyx/src/components/OnyxMoreList/types.ts
packages/sit-onyx/src/components/OnyxNavBar/OnyxNavBar.stories.ts
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxNavItem/OnyxNavItem.vue
packages/sit-onyx/src/composables/useMoreList.ts

Relates to #3059
- feat(useMoreList, OnyxMoreList): support "ltr" hiding direction
- Will be used for OnyxBreadCrumb(Item) truncation
- fix(useMoreListChild): fix `useMoreListChild` ResizeObserver only considering border-box instead of content-box

feat(useMoreList, OnyxMoreList): support "ltr" hiding direction 

---

apps/demo-app/app/components/BackgroundImageCard.vue
apps/demo-app/app/components/NavBar.vue

Relates to #3986
Add context area slot to the demo app nav bar so we can add a brand theme switch for our internal demo app deployment

feat(demo-app): add nav bar context area slot

---

.changeset/young-ghosts-begin.md
packages/sit-onyx/src/components/OnyxDataGrid/features/stickyColumns/stickyColumns.ts
packages/sit-onyx/src/components/OnyxDataGrid/features/stickyColumns/types.ts

Support passing refs to the useStickyColumns data grid feature so the project can e.g. implement a custom feature where the user can pin/unpin columns

feat(useStickyColumns): support passing refs as options

---

.changeset/ready-teeth-drop.md
packages/sit-onyx/src/components.spec.ts
packages/sit-onyx/src/components/OnyxBreadcrumbItem/OnyxBreadcrumbItem.vue
packages/sit-onyx/src/components/OnyxNavBar/modules/OnyxNavItem/OnyxNavItem.vue

Closes #4137
- Fixed by only performing teleport on client
- Added SSR testing for components

fix(OnyxBreadcrumb): Fix `can't access property "nodeType", container is null` hydration error
